{
  "hash": "702ac3cbf3a9469f271a90083847e132",
  "result": {
    "engine": "knitr",
    "markdown": "# The Variance Equation and $R^2$ {#sec-variance-accounting}\n\nWe have come a very long way! After learning how to build models, we saw how the model *explains* variability in the outcome variable.\n\nFrom this new perspective on models, we can say:\n\n::: {.callout-note}\nThe purpose of a model is to *explain* the variance in the outcome variable to whatever extent it can. \n:::\n\nWe also saw that we can measure the quality of a model by how much of the variability in the outcome variable it explains. In fact statisticians call this the $R^2$ of the model. See @eq-crude-rsq\n\n$$\nR^2\n=\n\\frac{\\text{Var}(\\text{model estimates})}\n     {\\text{Var}(\\text{outcome variable})}\n$$ {#eq-crude-rsq}\n \n\n\n::: {.callout-note icon=false}\n## Quick Check {.unnumbered}\n\nHow much variability in the outcome variable does the mean model with no explanatory variables explain?\n:::\n\n::: {.callout-note icon=false collapse=true}\n## Suggested answer {.unnumbered}\n\nThe model values in this case are fixed and have no variability. For example we might have a model like:\n\n$$\n\\widehat{\\text{customers}} = 124\n$$\n\nIn this case, the model estimates are the same for every row and hence have zero variance. The model does not expect any variability in the outcome variable, but there is variability in the outcome variable. So the model explains zero variability in the outcome variable. Therefore, $R^2$ is zero for this model.  \n:::\n\nSome models explain no variance in the outcome variable at all. Our first mean model had no variance at all, and therefore did not explain any variability in the outcome variable. On the other extreme, we can (theoretically) have models that explain *all* the variability in the outcome variable. This can only happen if in the real-world dataset we are looking at the outcome variable,miraculously, has a perfect linear relationship with the explanatory variable(s). In the case of a single numerical explanatory variable, all the points would have to fall along a straight line. This almost never happens in real life.\n\nWe will see an interesting relationship between variances in the context of linear models -- the so-called variance accounting equation. \n\nWe will see several examples of explaining variation and attach the name R-squared to a concept we have already studied.\n\nThis chapter mostly reinforces what you have already learned through many examples so that you can see recurring patterns in code and in inferring the model function or model equation.\n\n## The variance equation\n\nLet us take the mpg dataset, build a model to explain the highway mileage (column *hwy*) with *displacement* as the explanatory variable, and add the model estimates to the data frame.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  mutate(model_estimate = model_values(hwy ~ displ)) |> \n  select(displ, year, hwy, model_estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 234 x 4\n   displ  year   hwy model_estimate\n   <dbl> <int> <int>          <dbl>\n 1   1.8  1999    29           29.3\n 2   1.8  1999    29           29.3\n 3   2    2008    31           28.6\n 4   2    2008    30           28.6\n 5   2.8  1999    26           25.8\n 6   2.8  1999    26           25.8\n 7   3.1  2008    27           24.8\n 8   1.8  1999    26           29.3\n 9   1.8  1999    25           29.3\n10   2    2008    28           28.6\n# i 224 more rows\n```\n\n\n:::\n:::\n\n\nNow that we have the model estimates, we can extend the above code to compute the residuals as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  mutate(model_estimate = model_values(hwy ~ displ),\n         residual = hwy - model_estimate) |> \n  select(displ, year, hwy, model_estimate, residual)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 234 x 5\n   displ  year   hwy model_estimate residual\n   <dbl> <int> <int>          <dbl>    <dbl>\n 1   1.8  1999    29           29.3   -0.343\n 2   1.8  1999    29           29.3   -0.343\n 3   2    2008    31           28.6    2.36 \n 4   2    2008    30           28.6    1.36 \n 5   2.8  1999    26           25.8    0.188\n 6   2.8  1999    26           25.8    0.188\n 7   3.1  2008    27           24.8    2.25 \n 8   1.8  1999    26           29.3   -3.34 \n 9   1.8  1999    25           29.3   -4.34 \n10   2    2008    28           28.6   -0.636\n# i 224 more rows\n```\n\n\n:::\n:::\n\n\nWe can then compute the variance of the outcome variable, the model estimates, and the residuals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  mutate(model_estimate = model_values(hwy ~ displ),\n         residual = hwy - model_estimate) |> \n  summarize(var(hwy), var(model_estimate), var(residual))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n  `var(hwy)` `var(model_estimate)` `var(residual)`\n       <dbl>                 <dbl>           <dbl>\n1       35.5                  20.8            14.7\n```\n\n\n:::\n:::\n\n\nWhat do you see in the output? The variances of the model estimates and the residuals exactly add up to the variance of the outcome variable!\n\n$$\n\\underbrace{\\operatorname{Var}(\\text{customers})}_{\\substack{\n    \\text{total variance} \\\\\n    \\text{(i.e., variance in outcome variable)}\n  }}\n= \\underbrace{\\operatorname{Var}(\\widehat{\\text{customers}})}_{\\text{model estimate variance}}\n+ \\underbrace{\\operatorname{Var}(\\text{resid})}_{\\text{residual variance}}\n$$\n\nOr more generally as:\n\n$$\n\\operatorname{Var}(\\text{outcome variable}) \n= \\operatorname{Var}(\\text{model estimates}) \n+ \\operatorname{Var}(\\text{residuals})\n$$ {#eq-accounting-for-variance}\n\nIn the linear models that we build in this course, @eq-accounting-for-variance **always** holds!\n\nLet us try an example from our kiosk models. First the model with no explanatory variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  mutate(model_estimate = model_values(customers ~ 1),\n         residual = customers - model_estimate) |> \n  summarize(Total_variance = var(customers), \n            Model_estimate_variance = var(model_estimate), \n            Residual_variance = var(residual))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n  Total_variance Model_estimate_variance\n           <dbl>                   <dbl>\n1          1169.                       0\n# i 1 more variable: Residual_variance <dbl>\n```\n\n\n:::\n:::\n\n\nWhat just happened? Well, the model above with no explanatory variables has no variance and does not explain any variability. So the residual for each row is the full value of the outcome variable. Which is why you see that the variance of the residuals is equal to the variance of the outcome variables. The variance equation still holds!\n\nLet us try the model with just the kiosk as the explanatory variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  mutate(model_estimate = model_values(customers ~ kiosk),\n         residual = customers - model_estimate) |> \n  summarize(Total_variance = var(customers), \n            Model_estimate_variance = var(model_estimate), \n            Residual_variance = var(residual))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n  Total_variance Model_estimate_variance\n           <dbl>                   <dbl>\n1          1169.                    514.\n# i 1 more variable: Residual_variance <dbl>\n```\n\n\n:::\n:::\n\n\nAs we have already seen, this model explains 514 out of the total variance of 1169. The variance equation holds again.\n\nLet us now see the model with temperature and kiosk (without interaction effects).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  mutate(model_estimate = model_values(customers ~ temperature + kiosk),\n         residual = customers - model_estimate) |> \n  summarize(Total_variance = var(customers), \n            Model_estimate_variance = var(model_estimate), \n            Residual_variance = var(residual))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n  Total_variance Model_estimate_variance\n           <dbl>                   <dbl>\n1          1169.                   1005.\n# i 1 more variable: Residual_variance <dbl>\n```\n\n\n:::\n:::\n\n\nWe have seen this before too. This model explains 1005 out of 1169. The variance equation holds again.\n\nWe can try one with the *Boston_marathon* data frame. Let us use minutes as the explanatory variable and year as the explanatory variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBoston_marathon |> \n  mutate(model_estimate = model_values(minutes ~ year),\n         residual = minutes - model_estimate) |> \n  summarize(Total_variance = var(minutes), \n            Model_estimate_variance = var(model_estimate), \n            Residual_variance = var(residual))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n  Total_variance Model_estimate_variance\n           <dbl>                   <dbl>\n1           146.                    38.7\n# i 1 more variable: Residual_variance <dbl>\n```\n\n\n:::\n:::\n\n\nWhat? The variance equation does not seem to hold. But this is actually happening because of rounding.\n\nWe can make it print more digits for verification.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Run this code in RStudio\noptions(pillar.sigfig = 12)\nBoston_marathon |> \n  mutate(model_estimate = model_values(minutes ~ year),\n         residual = minutes - model_estimate) |> \n  summarize(Total_variance = var(minutes), \n            Model_estimate_variance = var(model_estimate), \n            Residual_variance = var(residual))\n```\n:::\n\n\nRun the above code in Rstudio and verify that the variance equation holds.\n\nLet us include sex as well and see how much improvement there is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Run this code in RStudio\noptions(pillar.sigfig = 12)\nBoston_marathon |> \n  mutate(model_estimate = model_values(minutes ~ year + sex),\n         residual = minutes - model_estimate) |> \n  summarize(Total_variance = var(minutes), \n            Model_estimate_variance = var(model_estimate), \n            Residual_variance = var(residual))\n```\n:::\n\n\n\n## Safe approach for computing $R^2$\n\nIn any of the prior examples, we can find the proportion of variance that the model explains by using @eq-crude-rsq-1.\n\n$$\nR^2\n=\n\\frac{\\text{Var}(\\text{model estimates})}\n     {\\text{Var}(\\text{outcome variable})}\n$$ {#eq-crude-rsq-1}\n\nHowever, this approach might not always work when we have missing values for the explanatory variables or the outcome variable. If some rows have rows with missing values for one or more explanatory variables, those rows will be left out of the *model_values* function and will end up with no model estimates. But the variance computations will still include all available values. So the number of rows on which the three variances are calculated could be mismatched and it will seem like the variance equation is not holding up.\n\nThe *txhousing* data frame provides an example.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntxhousing |> \n  mutate(model_estimate = model_values(sales ~ listings),\n         residual = sales - model_estimate) |>\n  summarize(Total_variance = var(sales),\n            Model_estimate_variance = var(model_estimate),\n            Residual_variance = var(residual))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n  Total_variance Model_estimate_variance\n           <dbl>                   <dbl>\n1             NA                      NA\n# i 1 more variable: Residual_variance <dbl>\n```\n\n\n:::\n:::\n\n\nWe see that the output is all NA. TWe can avoid this by using na.rm = TRUE in the *var* function. But that will result in the mismatch we spoke about in the prior paragraph.\n\nThe safe approach is to use the function that is explicitly provided for computing $R^2$ -- that function is *R2()*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntxhousing |> \n  model_train(sales ~ listings) |> \n  R2()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     n k Rsquared     F adjR2 p df.num df.denom\n1 7176 1    0.849 40366 0.849 0      1     7174\n```\n\n\n:::\n:::\n\n\nFrom the output we see an $R^2$ value of 85%.\n\nLet us check the computed $R^2$ value for some of our earlier computations by using both methods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## R-squared by method 1\nkiosk_beach_mall_temp |> \n  mutate(model_estimate = model_values(customers ~ temperature + kiosk),\n         residual = customers - model_estimate) |> \n  summarize(Total_variance = var(customers), \n            Model_estimate_variance = var(model_estimate), \n            Residual_variance = var(residual))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 3\n  Total_variance Model_estimate_variance\n           <dbl>                   <dbl>\n1          1169.                   1005.\n# i 1 more variable: Residual_variance <dbl>\n```\n\n\n:::\n:::\n\n\nThis gives us 1005/1169 or 86%.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  model_train(customers~ temperature + kiosk) |> \n  R2()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   n k Rsquared   F adjR2 p df.num df.denom\n1 50 2     0.86 144 0.854 0      2       47\n```\n\n\n:::\n:::\n\n\nWe get the same 86%.\n\nGoing forward, we will use the *R2()* function for computing $R^2$.\n\n$$\n\\hat{y} =\n\\underbrace{\\beta_0}_{\\text{intercept}}\n+\n\\underbrace{\\beta_1 x}_{\\text{slope effect}}\n$$\n\n\n",
    "supporting": [
      "accounting-for-variance_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}