{
  "hash": "b2a8827b3c3013859b9aab7d249b7178",
  "result": {
    "engine": "knitr",
    "markdown": "# Explaining Variation in Outcome Variable with Models {#sec-explaining-variation}\n\nIn the previous chapter, we learned how to compute **model values** and **residuals**. For each day, the model gave us a predicted number of customers, and the residual told us how far off that prediction was from reality.\n\nAmanda asked the interns to come over the the mall kiosk so that they could get a feel for the actual operation while they discussed how to take this project forward. She seemed a bit concerned.\n\n\"You have helped us improve efficiency over the past few months. I have been able to maintain stable staffing levels while not overstaffing on slow days, or under-staffing on busy days. \n\nI have seen that using data properly does indeed help me to make better decisions and am planning to sign up for a service that will give me more data about our operations ... but they are pricey and I don't want to spend the money without knowing how much potential we have to improve our models. I want to know how much room we have to improve. So my first question for you all is:\n\n> *How good is this model, really? Do we have room to improve? Or have we hit the ceiling?*\n\nWell, that was three questions ...\" Amanda said with a smile. \"Why don't you discuss and we can talk about it after a while?\"\n\nThe interns are about to discover an important concept in linear models (the kind we build in this course) -- **variance of the outcome variable is split between what the model explains and what it does not**.\n\n## Model as an explainer of variation in the outcome variable\n\nSteve began \"To map back to what we did in our last few months for Amanda, we might say that when look at the outcome variable -- the number of customers each day --  and see the variability. Initially when Amanda just gave us the number of customers alone, we could not do much and suggested that the best she could do was to use the average as the estimate each day for both kiosks.\n\nSome of the variability in the number of customers arises because of their location. The beach kiosk has its pattern and the mall one has its quirks. For example, on average the beach kiosk saw 40 more customers each day. So using the same staffing level for both kiosks does not make sense.\n\nSo, one reason for the variation in the numbers was the kiosk each number was associated with. Once Amanda gave us the kiosk for each number in the data, we were hen able to give her a separate estimate for each kiosk and she confirmed that it improved matters for her.\"\"\n\n\n::: {.callout-important}\nThe model that used kiosk as the explanatory variable explained, or clarified, why there was some variability in the number of customers overall, but it did not explain all of the variability. For example, we know that the overall average number of customers was around 120 while the average for the mall was around 100 and for the beach was around 140. So if we look at the sales for a given day and see that it is 150, we can be pretty sure (but not 100% certain) that this sale likely was for the beach kiosk. So, in this sense, the kiosk location \"explains\" the number of customers.\n:::\n\n Angela joined in: \"But, there is still variability in the sales for each kiosk. That is, not all the numbers for the beach kiosk are the same, no=r are the numbers for the mall kiosk the same. So just knowing the kiosk location did not tell us the whole story. We still had some more variability to explain. We added temperature and that improved matters for Amanda.\"\n \n ::: {.callout-important}\n Then we added temperature as an explanatory variable and saw that the predictions got better. \n \n We know that the average number of customers for the beach kiosk is close to 140 and that temperature has a role to play in the number of customers. \n \n Let us say in the data we see 150 customers (above average) for a given day at the beach kiosk. WHat does that say about the likely temperature on that day? It would be reasonable to expect that the temperature was also above average on that day -- of course we cannot be 100% sure, but that would be a reasonable expectation. In this sense the model with kiosk and temperature as explanatory variables \"explains\" the number of customers.\n :::\n \nIgor and Dave almost simultaneously say \"WHat if together the liosk locatio and the temperature tell us everything we need to know. What if they eplain all the variability in the number of customers?\"\n\nSuzie immediately says \"That would mean that the model with kiosk location and temperature gives estimates that match actual values *exactly*! Does it?\"\n\nPeter brings up a table showing the original data and the model estimates (tbl-temp-kiosk-model-estimates) using the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n  kiosk_beach_mall_temp |> \n    mutate(mod_est = model_values(customers ~ temperature + kiosk))\n```\n:::\n\n\n|day | customers|kiosk | temperature| mod_est|\n|:---|---------:|:-----|-----------:|-------:|\n|D01 |        67|Mall  |        58.6|      77|\n|D02 |       119|Mall  |        73.6|     116|\n|D03 |        93|Mall  |        62.3|      87|\n|D04 |       100|Mall  |        76.5|     124|\n|D05 |       130|Mall  |        78.2|     128|\n|D06 |        80|Mall  |        51.4|      59|\n|D07 |        94|Mall  |        65.8|      96|\n|D08 |       124|Mall  |        76.8|     125|\n|D09 |       108|Mall  |        66.5|      98|\n|D10 |       103|Mall  |        63.7|      91|\n|D11 |       125|Mall  |        78.7|     130|\n|D12 |       100|Mall  |        63.6|      90|\n|D13 |       103|Mall  |        70.3|     108|\n|D14 |        96|Mall  |        67.2|     100|\n|D15 |        73|Mall  |        53.1|      63|\n|D16 |       106|Mall  |        77.0|     125|\n|D17 |        82|Mall  |        57.4|      74|\n|D18 |        60|Mall  |        51.3|      58|\n|D19 |       113|Mall  |        59.8|      80|\n|D20 |       131|Mall  |        78.6|     129|\n|D21 |       101|Mall  |        76.7|     124|\n|D22 |       100|Mall  |        70.8|     109|\n|D23 |        97|Mall  |        69.2|     105|\n|D24 |       127|Mall  |        79.8|     132|\n|D25 |       102|Mall  |        69.7|     106|\n|D01 |       168|Beach |        71.3|     167|\n|D02 |       164|Beach |        66.3|     154|\n|D03 |       162|Beach |        67.8|     158|\n|D04 |       129|Beach |        58.7|     134|\n|D05 |       106|Beach |        54.4|     123|\n|D06 |       203|Beach |        78.9|     187|\n|D07 |       187|Beach |        77.1|     182|\n|D08 |       154|Beach |        70.7|     165|\n|D09 |       182|Beach |        73.9|     174|\n|D10 |       118|Beach |        50.7|     113|\n|D11 |       146|Beach |        64.3|     149|\n|D12 |       191|Beach |        72.8|     171|\n|D13 |       105|Beach |        56.5|     128|\n|D14 |       136|Beach |        59.5|     136|\n|D15 |       134|Beach |        56.9|     130|\n|D16 |       122|Beach |        54.3|     123|\n|D17 |       148|Beach |        62.4|     144|\n|D18 |       138|Beach |        62.4|     144|\n|D19 |       131|Beach |        61.1|     140|\n|D20 |       106|Beach |        54.6|     124|\n|D21 |       120|Beach |        54.2|     122|\n|D22 |       115|Beach |        57.0|     130|\n|D23 |       146|Beach |        64.0|     148|\n|D24 |       128|Beach |        58.0|     132|\n|D25 |       217|Beach |        75.7|     178|\n\n: Kiosk data and model estimates for customers ~ temperature + kiosk (model estimates rounded){#tbl-temp-kiosk-model-estimates}\n\nAngela says \"Darn. The predictions look reasonably close, but they are nowhere near exact. So the model is *not perfect*. How can we improve it?\"\n\nIgor says \"Guys, I think I understand this a bit better now. It makes sense that we cannot estimate the exact number of customers just using the temperature and kiosk location. After all, the real world is more complex than that. MAny other factors can and do affect the number of customers.\"\n\nDave says \"Yes, the other day I was at the beach on a nice warm day and yet I only saw a few people out on the beach. We had an important playoff game in town.\"\n\nAngela then says \"So it looks like we cannot improve things for Amanda unless she gives us more data. But can we answer her question of how good the model is? May be it is not *exact*, but it might still be good enough that she should not be spending money to get more data. I mean the extra benefit might not be worth the cost.\"\n\nSuzie has an idea \"Let us put some hard numbers on this OK? If we are trying to find out how much variability the model *explains*, well, how much variability is there to explain in the first place?\"\n\nIgor lights up \"We are talking about variability in the daily number of customers. Why not just use the variance of that variable?\"\n\nSuzie writes code immediately to calculate that:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  summarize(cust_var = var(customers))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  cust_var\n     <dbl>\n1    1169.\n```\n\n\n:::\n:::\n\n\nDave \"OK. Where do we go from here?\"\n\nAngela \"Guys, let us slow don a wee bit here. Shall we go back to the simplest model we had and start thinking from there? That might help us to understand this better.\"\n\nIgor \"OK. In our simplest model, we just predicted the average of the number of customers, completely ignoring the kiosk location or the temperature because at that time we did not have those variables. SO how much variation does that model explain?\"\n\nAgain Suzie whips out code and produces @tbl-mean-model-estimates-kiosk-1:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#|\nkiosk_beach_mall_temp |> \n  mutate(mod_val = model_values(customers ~ 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 50 x 5\n   day   customers kiosk temperature mod_val\n   <chr>     <dbl> <chr>       <dbl>   <dbl>\n 1 D01          67 Mall         58.6    124.\n 2 D02         119 Mall         73.6    124.\n 3 D03          93 Mall         62.3    124.\n 4 D04         100 Mall         76.5    124.\n 5 D05         130 Mall         78.2    124.\n 6 D06          80 Mall         51.4    124.\n 7 D07          94 Mall         65.8    124.\n 8 D08         124 Mall         76.8    124.\n 9 D09         108 Mall         66.5    124.\n10 D10         103 Mall         63.7    124.\n# i 40 more rows\n```\n\n\n:::\n:::\n\n\n| customers|kiosk | temperature| mod_val|\n|---------:|:-----|-----------:|-------:|\n|  66.78076|Mall  |    58.62733|     124|\n| 118.66666|Mall  |    73.64915|     124|\n|  93.43390|Mall  |    62.26931|     124|\n| 100.36348|Mall  |    76.49052|     124|\n| 130.40991|Mall  |    78.21402|     124|\n|  79.90381|Mall  |    51.36669|     124|\n|  93.75559|Mall  |    65.84316|     124|\n| 124.09655|Mall  |    76.77257|     124|\n| 108.27050|Mall  |    66.54305|     124|\n| 103.27566|Mall  |    63.69844|     124|\n| 124.68300|Mall  |    78.70500|     124|\n| 100.05773|Mall  |    63.60002|     124|\n| 103.27945|Mall  |    70.32712|     124|\n|  95.67201|Mall  |    67.17900|     124|\n|  73.28583|Mall  |    53.08774|     124|\n| 106.21587|Mall  |    76.99475|     124|\n|  81.82622|Mall  |    57.38263|     124|\n|  60.35403|Mall  |    51.26179|     124|\n| 112.81761|Mall  |    59.83762|     124|\n| 130.52786|Mall  |    78.63511|     124|\n| 100.83468|Mall  |    76.68618|     124|\n| 100.07004|Mall  |    70.78410|     124|\n|  96.94184|Mall  |    69.21520|     124|\n| 127.44578|Mall  |    79.82809|     124|\n| 102.03122|Mall  |    69.67117|     124|\n| 168.20985|Beach |    71.25591|     124|\n| 163.65952|Beach |    66.32198|     124|\n| 162.31480|Beach |    67.82426|     124|\n| 129.13389|Beach |    58.67479|     124|\n| 106.40419|Beach |    54.41341|     124|\n| 203.48841|Beach |    78.89073|     124|\n| 187.48142|Beach |    77.06897|     124|\n| 153.84239|Beach |    70.72116|     124|\n| 181.60487|Beach |    73.86402|     124|\n| 118.03537|Beach |    50.73841|     124|\n| 145.86710|Beach |    64.33388|     124|\n| 190.64386|Beach |    72.75379|     124|\n| 104.94268|Beach |    56.49224|     124|\n| 135.97914|Beach |    59.54543|     124|\n| 134.44498|Beach |    56.94877|     124|\n| 122.31435|Beach |    54.28400|     124|\n| 148.15289|Beach |    62.43639|     124|\n| 138.31947|Beach |    62.41173|     124|\n| 130.90118|Beach |    61.06536|     124|\n| 106.01421|Beach |    54.57334|     124|\n| 119.50052|Beach |    54.16418|     124|\n| 115.43508|Beach |    56.99102|     124|\n| 145.73808|Beach |    63.97887|     124|\n| 127.90567|Beach |    57.97918|     124|\n| 217.16607|Beach |    75.73483|     124|\n\n: Model estimates for customers ~ 1, same as the mean model (rounded) {#tbl-mean-model-estimates-kiosk-1}\n\nIgor says \"But I thought that if we had only the number of customers and nothing else, then the model estimate is just the average.\"\n\nPeter \"Yes, when we use customers ~ 1 in the *model_values* function, that is exactly what it does. The average is 123.8. We can just let *model_values* do the dirty work for us! The model equation would be\" and he wrote down @q-kiosk-mean-model-2.\n\n$$\n\\widehat{\\text{customers}} = 124\n$$ {#eq-kiosk-mean-model-2}\n\n\nAngela \"So the model estimates for every row are the same? That actually makes sense because it is just the average no matter what. That means the model values have no variance!\"\n\nDave says \"Yes, that makes sense too because this model customers ~ 1 has no explanatory variables and so it has no basis to say anything different for each row. It is unable to take the kiosk location or the temperature to say something specific for each row based on those.\"\n\nAngela \"So, according to this model, given what it is allowed to use, all the rows should have the same number of customers. It has no clue why they differ. I get it now. It is unable to explain any of the variation in the number of customers!\"\n\nIgor \"I think Angela hit upon a great insight. The variance of the model estimates actually represents the *amount of variation that the model explains*! If the model estimates have no variance as in the current situation, then the model explains nothing.\"\n\nDavid \"I sure am happy that we managed to get away with giving Angela a model that *explained nothing* on the first day we met! But then that is all we could do with the data we had!\"\n\n\"Let me make sure I understand\" says Peter. \"You are sying that on the one side we have the variance of the outcome variable (number of customers) and on the other side we have the variance of the model estimates, or put differently, the amount of variation the model expects.\"\n\n\"Yes\" Igor responds. Our actual values can vary all over the place, but the model values, as we have built the model, have to fit on a straight line. they atr  much more constrained than real-life. SO the variance of the model estimates will always be lower.\"\n\nSuzie says \"Let us make all this concrete, can we?\" and first calculates the variance of the number of customers by itself. That is the amout of variation that a model must try to explain.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  summarize(outcome_var = var(customers))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  outcome_var\n        <dbl>\n1       1169.\n```\n\n\n:::\n:::\n\n\n\"OK\" Dave says. 1169 is our baseline. A perfect model will explain all of it.\"\n\n\"But\" says Suzie \"We are building only linear models and our model estimates will always fall on a straight line. Our points as they stand are scattered and no single straight line can ever catch all of them. Because of this, no model we build can ever hope to explain all of the variance in the number of customers.\"\n\nPeter \"That's a sobering thought. Taking it to the next step, why don't we see how much variability the model with separate means for the two kiosks explains? \n\nAngela writes the following code to build the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  model_train(customers ~ kiosk) |> \n  coef()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   kioskMall \n      146.2       -44.9 \n```\n\n\n:::\n:::\n\n\nAngela continues \"So, the model function is\" and writes\n\n$$\n\\widehat{\\text{num customers}} = 146 \n\\begin{cases}\n+0 & \\text{if } \\text{kiosk} = \\text{\"Beach\"} \\\\\n-45 & \\text{if } \\text{kiosk} = \\text{\"Mall\"} \n\\end{cases}\n$$ {#eq-kiosk-cat-model-3}\n\nPeter then joins in. \"Let us compute the variances. I am not bringing in *temperature* yet.\" He writes this code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  mutate(mod_est = model_values(customers ~ kiosk)) |>\n  summarize(kiosk_model_est_var = var(mod_est))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  kiosk_model_est_var\n                <dbl>\n1                514.\n```\n\n\n:::\n:::\n\n\n\"OK\" says Angela. \"This model explains less than half of the total variance. To be more precise, it explains 514/1169 or 44% of the total variance.\"  \n\n\"Wow!\" David says. \"Although the model seems to not be great, Angela has condensed the idea of measuring a model's quality into a single number! Pretty statistical approach if you ask me.\"\n\nIgor summarizes. \"So we have it. The quality of the model is just the variance of the model estimates divided by the variance of the ourcome variable.\" And he writes @eq-model-quality:\n\n$$\n\\text{Model quality}\n=\n\\frac{\\text{Var}(\\text{model estimates})}\n     {\\text{Var}(\\text{outcome})}\n$$ {#eq-model-quality}\n\nPeter cannot wait. \"How about the model that includes temperature as well? Does it improve the quality? Let's check.\" and he writes the following code.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  mutate(temp_kiosk_mod_est = model_values(customers ~ temperature + kiosk)) |>\n  summarize(temp_kiosk_mod_est_var = var(temp_kiosk_mod_est))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  temp_kiosk_mod_est_var\n                   <dbl>\n1                  1005.\n```\n\n\n:::\n:::\n\n\nAngela exults \"Wow! This model explains 1005 out of has a variance of 1169. Does that mean that it explains 1005/1169, or 86% of the variability in customers? What is the model equation for this?\"\"\n\nIgor says \"You better believe it! Indeed it does.\" He then wrote the code and wrote out the model equation too.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  model_train(customers ~ temperature + kiosk) |> \n  coef()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) temperature   kioskMall \n      -18.4         2.6       -56.6 \n```\n\n\n:::\n:::\n\n\nThey reconstructed the model equation @eq-kiosk-mode-no-intxn-2 from the output.\n\n$$\n\\widehat{\\text{customers}} = -18.4 + 2.6\\, \\text{temperature} +\n\\begin{cases}\n0 & \\text{if } \\text{kiosk} = \\text{\"Beach\"} \\\\\n-57 &\\text{if } \\text{kiosk} = \\text{\"Mall\"}\n\\end{cases}\n$$ {#eq-kiosk-mode-no-intxn-2}\n\n\nDavid recalled their whole discussion about *interaction effects* and asked, \"Hey Igor or Suzie, by any chance, did Dr. Berlinsky show either of you a way by which we can build a model that includes the fancy *interaction effect*? We can then try to see how much explanatory quality we can gain by including that.\"\n\n\"He did show me the code. In fact it requires just changing a single character!\" Igor said and wrote it.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkiosk_beach_mall_temp |> \n  mutate(temp_kiosk_intxn_mod_est = model_values(customers ~ temperature * kiosk)) |>\n  summarize(temp_kiosk_mod_est_var = var(temp_kiosk_intxn_mod_est))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  temp_kiosk_mod_est_var\n                   <dbl>\n1                  1066.\n```\n\n\n:::\n:::\n\n\nAngela observed \"Well, that explains 1066 out of 1169 which is 91%.\"\n\nSuzie added \"Interpreting the coefficients is complicated, but Dr. B assured me that the net model is exactly the same as the two separate models we gave Amanda.\"\n\nAmanda settled for @eq-kiosk-mode-no-intxn-2 as the model that best balances operating efficiency and complexity.\n\nFor the moment she decided that the current models were sufficiently good that she need not spend the money to get more data.\n\n",
    "supporting": [
      "variance-analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}