<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>21&nbsp; Hypothesis Testing – Introduction to Business Statistics: A Modeling Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../modules/07-probability/probability-distributions.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-985aa47af68dae11cd4d235c71fb941e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6598efebc0fc82f63c3510b9ac47738c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Introduction to Business Statistics: A Modeling Approach</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/kviswana/bus-stats-quarto-book/issues/new?title=Book%20issue%20report&amp;labels=bug&amp;body=Page%20URL%3A%20%0A%0ASection%20Title%3A%20%0ADescribe%20the%20issue%3A%20%0A%0AIf%20this%20is%20a%20typo%2C%20please%20suggest%20a%20fix%3A%20" target="_blank"> <i class="bi bi-bug" role="img">
</i> 
<span class="menu-text">Report a bug</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../modules/07-probability/07-overview.html">Probability</a></li><li class="breadcrumb-item"><a href="../../modules/07-probability/hypothesis-testing-new.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../../index.html" class="sidebar-logo-link">
      <img src="../../images/logo-dark.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Business Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data, Visualization, and Patterns</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/01-data-visualization/01-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1: Data, Visualization &amp; Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/01-data-visualization/data-frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Frames and Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/01-data-visualization/point-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploring Relationships through Scatterplots</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Variation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/02-variability/02-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2: Variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/02-variability/violin-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Using Violin Plots to Visualize Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/02-variability/variance-and-sd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variance and standard deviation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction to models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/03-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 3: Introduction to models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/path-to-models-story.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">The Simplest Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/category-means-story.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Category Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/intro-to-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">What is a model?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/visualizing-simple-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Visualizing Mean Models</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">More on models – least squares</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/04-more-on-models/04-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4: Linear Regression Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/04-more-on-models/line-of-best-fit-story.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Line of Best Fit</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/04-more-on-models/visualizing-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Visualizing Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/04-more-on-models/finding-the-model-function.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Finding the Model Function</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/04-more-on-models/model-with-cat-and-num-explanatories-story.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Amanda’s New Challenge</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Explanatory Power of a Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/05-explanatory-power-of-models/05-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 5: Explanatory Power of a Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/05-explanatory-power-of-models/explain-as-used-in-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title"><em>Explain</em> as used in Statistics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/05-explanatory-power-of-models/variance-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Using Models to Explain Variation in Outcome Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/05-explanatory-power-of-models/accounting-for-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Variance Equation and <span class="math inline">\(R^2\)</span></span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/05-explanatory-power-of-models/adjustment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Adjustment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Transitioning to inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/06-inference/06-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6: Transitioning to Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/06-inference/populations-and-samples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Populations and samples</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/06-inference/inference-from-single-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference Based on a Single Sample</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/06-inference/confidence-interval-examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Visualizing models and Computing Confidence Intervals</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/07-probability/07-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 7: Population, Samples and Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/07-probability/probability-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/07-probability/hypothesis-testing-new.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#when-do-we-believe-something" id="toc-when-do-we-believe-something" class="nav-link active" data-scroll-target="#when-do-we-believe-something"><span class="header-section-number">21.1</span> When Do We Believe Something?</a></li>
  <li><a href="#our-running-example-a-new-training-programme" id="toc-our-running-example-a-new-training-programme" class="nav-link" data-scroll-target="#our-running-example-a-new-training-programme"><span class="header-section-number">21.2</span> Our Running Example: A New Training Programme</a></li>
  <li><a href="#the-null-and-alternate-hypotheses" id="toc-the-null-and-alternate-hypotheses" class="nav-link" data-scroll-target="#the-null-and-alternate-hypotheses"><span class="header-section-number">21.3</span> The Null and Alternate Hypotheses</a></li>
  <li><a href="#beyond-reasonable-doubt-connecting-to-confidence-intervals" id="toc-beyond-reasonable-doubt-connecting-to-confidence-intervals" class="nav-link" data-scroll-target="#beyond-reasonable-doubt-connecting-to-confidence-intervals"><span class="header-section-number">21.4</span> Beyond Reasonable Doubt: Connecting to Confidence Intervals</a></li>
  <li><a href="#the-two-possible-errors" id="toc-the-two-possible-errors" class="nav-link" data-scroll-target="#the-two-possible-errors"><span class="header-section-number">21.5</span> The Two Possible Errors</a>
  <ul class="collapse">
  <li><a href="#type-1-error-a-false-alarm" id="toc-type-1-error-a-false-alarm" class="nav-link" data-scroll-target="#type-1-error-a-false-alarm"><span class="header-section-number">21.5.1</span> Type 1 Error: A False Alarm</a></li>
  <li><a href="#type-2-error-a-missed-signal" id="toc-type-2-error-a-missed-signal" class="nav-link" data-scroll-target="#type-2-error-a-missed-signal"><span class="header-section-number">21.5.2</span> Type 2 Error: A Missed Signal</a></li>
  </ul></li>
  <li><a href="#formulating-hypotheses-examples-across-domains" id="toc-formulating-hypotheses-examples-across-domains" class="nav-link" data-scroll-target="#formulating-hypotheses-examples-across-domains"><span class="header-section-number">21.6</span> Formulating Hypotheses: Examples Across Domains</a>
  <ul class="collapse">
  <li><a href="#example-1-a-new-advertising-campaign-business" id="toc-example-1-a-new-advertising-campaign-business" class="nav-link" data-scroll-target="#example-1-a-new-advertising-campaign-business"><span class="header-section-number">21.6.1</span> Example 1: A New Advertising Campaign (Business)</a></li>
  <li><a href="#example-2-quality-control-in-manufacturing-business" id="toc-example-2-quality-control-in-manufacturing-business" class="nav-link" data-scroll-target="#example-2-quality-control-in-manufacturing-business"><span class="header-section-number">21.6.2</span> Example 2: Quality Control in Manufacturing (Business)</a></li>
  <li><a href="#example-3-loan-default-risk-finance" id="toc-example-3-loan-default-risk-finance" class="nav-link" data-scroll-target="#example-3-loan-default-risk-finance"><span class="header-section-number">21.6.3</span> Example 3: Loan Default Risk (Finance)</a></li>
  <li><a href="#example-4-a-new-drug-everyday-life-health" id="toc-example-4-a-new-drug-everyday-life-health" class="nav-link" data-scroll-target="#example-4-a-new-drug-everyday-life-health"><span class="header-section-number">21.6.4</span> Example 4: A New Drug (Everyday Life / Health)</a></li>
  <li><a href="#example-5-a-sports-performance-claim-sports" id="toc-example-5-a-sports-performance-claim-sports" class="nav-link" data-scroll-target="#example-5-a-sports-performance-claim-sports"><span class="header-section-number">21.6.5</span> Example 5: A Sports Performance Claim (Sports)</a></li>
  <li><a href="#example-6-employee-absenteeism-business-hr" id="toc-example-6-employee-absenteeism-business-hr" class="nav-link" data-scroll-target="#example-6-employee-absenteeism-business-hr"><span class="header-section-number">21.6.6</span> Example 6: Employee Absenteeism (Business / HR)</a></li>
  <li><a href="#example-7-online-checkout-redesign-business-technology" id="toc-example-7-online-checkout-redesign-business-technology" class="nav-link" data-scroll-target="#example-7-online-checkout-redesign-business-technology"><span class="header-section-number">21.6.7</span> Example 7: Online Checkout Redesign (Business / Technology)</a></li>
  </ul></li>
  <li><a href="#a-note-on-what-failing-to-reject-really-means" id="toc-a-note-on-what-failing-to-reject-really-means" class="nav-link" data-scroll-target="#a-note-on-what-failing-to-reject-really-means"><span class="header-section-number">21.7</span> A Note on What “Failing to Reject” Really Means</a></li>
  <li><a href="#sec-coin-toss-example" id="toc-sec-coin-toss-example" class="nav-link" data-scroll-target="#sec-coin-toss-example"><span class="header-section-number">21.8</span> Numerical Example: Revisiting our clairvoyant coin-toss guessing friend</a>
  <ul class="collapse">
  <li><a href="#the-setup" id="toc-the-setup" class="nav-link" data-scroll-target="#the-setup"><span class="header-section-number">21.8.1</span> The Setup</a></li>
  <li><a href="#the-logic" id="toc-the-logic" class="nav-link" data-scroll-target="#the-logic"><span class="header-section-number">21.8.2</span> The Logic</a></li>
  <li><a href="#watching-the-evidence-accumulate" id="toc-watching-the-evidence-accumulate" class="nav-link" data-scroll-target="#watching-the-evidence-accumulate"><span class="header-section-number">21.8.3</span> Watching the Evidence Accumulate</a></li>
  <li><a href="#what-this-tells-us" id="toc-what-this-tells-us" class="nav-link" data-scroll-target="#what-this-tells-us"><span class="header-section-number">21.8.4</span> What This Tells Us</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../modules/07-probability/07-overview.html">Probability</a></li><li class="breadcrumb-item"><a href="../../modules/07-probability/hypothesis-testing-new.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-hypothesis-testing" class="quarto-section-identifier"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis Testing</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Statistics, at its core, is about making decisions under uncertainty. We rarely have complete information, yet we still have to act. Should we launch a new product? Is this marketing campaign actually working? Did the new training programme improve employee performance? In each case, we are asking: <em>do I have enough evidence to believe something?</em></p>
<p>This chapter is about the formal framework statisticians use to answer that question. It is called <em>hypothesis testing</em>, and by the end of this chapter you will be able to think through any real-world claim with the same structured logic that underpins scientific and business decision-making.</p>
<p>We will build up the ideas using a single running example, and then explore how the same framework applies across business, everyday life, and sports.</p>
<section id="when-do-we-believe-something" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="when-do-we-believe-something"><span class="header-section-number">21.1</span> When Do We Believe Something?</h2>
<p>Before we get into any statistics, let us think about how human beings naturally decide whether to believe a claim.</p>
<p>Imagine a friend tells you: “I can predict the outcome of a coin flip every single time.” You are sceptical – as you should be. So you test them. You flip a coin, they predict it correctly. Do you believe them now?</p>
<p>Probably not. One correct prediction could easily be a fluke. So you flip again. They get it right. And again. And again. After ten correct predictions in a row, you are starting to raise an eyebrow. After twenty in a row, you are genuinely astonished. At some point, you cross a threshold where the evidence is so compelling that you abandon your scepticism and conclude: <em>this is not a fluke</em>.</p>
<p>That threshold – the point where coincidence becomes too implausible – is the beating heart of hypothesis testing.</p>
<p>The same logic plays out in courts of law. A jury does not require <em>certainty</em> to convict. Certainty is almost never available. What they require is proof <em>beyond a reasonable doubt</em>. This phrase has a precise meaning: the evidence must be strong enough that any reasonable person would be convinced. It does not mean zero chance of being wrong. It means the chance of being wrong is small enough that we are willing to act as though we are right.</p>
<p>Statistics formalises this intuition into a rigorous procedure.</p>
</section>
<section id="our-running-example-a-new-training-programme" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="our-running-example-a-new-training-programme"><span class="header-section-number">21.2</span> Our Running Example: A New Training Programme</h2>
<p>A large retail company has introduced a new sales training programme for its staff. Before the programme, the average number of sales per employee per week was 42. The HR director wants to know: <em>has the training actually improved sales performance?</em></p>
<p>This is a hypothesis testing question. Let us use it to build up all the key ideas.</p>
</section>
<section id="the-null-and-alternate-hypotheses" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="the-null-and-alternate-hypotheses"><span class="header-section-number">21.3</span> The Null and Alternate Hypotheses</h2>
<p>The first step in hypothesis testing is to state clearly what we are testing. We do this by formulating two competing claims.</p>
<p>The <strong>null hypothesis</strong> is the conservative, “nothing has changed” claim. It represents the status quo – the world as it was before, or as we would expect it to be if nothing interesting were happening. In our example:</p>
<blockquote class="blockquote">
<p><strong>Null hypothesis:</strong> The training programme has had no effect. The average sales per employee per week is still 42.</p>
</blockquote>
<p>The <strong>alternate hypothesis</strong> is the claim we are trying to find evidence <em>for</em>. It is the interesting claim – the one that, if true, would matter. In our example:</p>
<blockquote class="blockquote">
<p><strong>Alternate hypothesis:</strong> The training programme has improved sales. The average sales per employee per week is now greater than 42.</p>
</blockquote>
<p>This asymmetry is important and worth dwelling on. We do not treat the two hypotheses as equals. The null hypothesis gets the benefit of the doubt. We start by <em>assuming it is true</em>, and we only abandon it if the data provide compelling evidence against it. Just as in a court of law, the defendant (the null hypothesis) is presumed innocent until proven guilty beyond a reasonable doubt.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick Check
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the training programme example, why is “the programme has no effect” the null hypothesis rather than the alternate?</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the null hypothesis always represents the default, conservative position – the world as it was before any intervention. We require evidence to move <em>away</em> from that position, not evidence to stay there. Assuming the programme works without evidence would be the wrong starting point; it would be too easy to claim success without justification.</p>
</div>
</div>
</div>
</section>
<section id="beyond-reasonable-doubt-connecting-to-confidence-intervals" class="level2" data-number="21.4">
<h2 data-number="21.4" class="anchored" data-anchor-id="beyond-reasonable-doubt-connecting-to-confidence-intervals"><span class="header-section-number">21.4</span> Beyond Reasonable Doubt: Connecting to Confidence Intervals</h2>
<p>You have already encountered the idea of a 95% confidence interval in an earlier chapter. Recall that a 95% confidence interval around an estimate says: if we repeated this study many times, 95% of the intervals we constructed would contain the true value.</p>
<p>Hypothesis testing is built on the same underlying logic. The standard threshold used in most fields is 95% confidence – or equivalently, we are willing to tolerate only a 5% chance of being wrong when we reject the null hypothesis.</p>
<p>In our example: after the training programme, suppose we measure the sales of a sample of employees and compute their average. If that average is only slightly above 42 – say, 43 – we would not be very impressed. A difference that small could easily have arisen by chance, even if the programme had no real effect.</p>
<p>But if the average is 56, that is a very different story. A gap that large would be extremely unlikely to occur purely by chance if the null hypothesis were true. The data are, in effect, screaming at us that something has changed.</p>
<p>The 95% threshold formalises this. We ask: <em>if the null hypothesis were true, how likely would it be to see data at least as extreme as what we actually observed?</em> If that probability is less than 5%, we declare that the result is statistically significant and we reject the null hypothesis in favour of the alternate.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick Check
</div>
</div>
<div class="callout-body-container callout-body">
<p>We observe that the average sales per employee after the training programme is 44.5, compared to the previous average of 42. Without doing any calculations, what additional information would you need to decide whether this difference is statistically significant?</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You would need to know how much variability there is in the sales data. If sales vary enormously from week to week and employee to employee, then a difference of 2.5 units could easily be random noise. If sales are very consistent, even a small difference might be meaningful. You would also want to know how large the sample was – a difference based on 500 employees is far more convincing than the same difference based on 5 employees.</p>
</div>
</div>
</div>
</section>
<section id="the-two-possible-errors" class="level2" data-number="21.5">
<h2 data-number="21.5" class="anchored" data-anchor-id="the-two-possible-errors"><span class="header-section-number">21.5</span> The Two Possible Errors</h2>
<p>Here is the uncomfortable truth: we can never be completely certain. Even at the 95% confidence threshold, we will be wrong 5% of the time. And there are actually two distinct ways we can be wrong. Understanding them is crucial, because the consequences of each type of error are very different.</p>
<section id="type-1-error-a-false-alarm" class="level3" data-number="21.5.1">
<h3 data-number="21.5.1" class="anchored" data-anchor-id="type-1-error-a-false-alarm"><span class="header-section-number">21.5.1</span> Type 1 Error: A False Alarm</h3>
<p>A <strong>Type 1 error</strong> occurs when we reject the null hypothesis even though it is actually true. In other words, we conclude that something interesting is happening when in fact nothing has changed.</p>
<p>In our training programme example, a Type 1 error would mean concluding that the programme improved sales – and perhaps paying to roll it out company-wide – when in reality the improvement we saw was just random chance and the programme did nothing.</p>
<p>This is the <em>false alarm</em> error. We have been fooled by noise into thinking there is a signal.</p>
<p>The 5% threshold we discussed earlier is directly related to this error. When we require 95% confidence to reject the null hypothesis, we are saying: we are willing to make a Type 1 error at most 5% of the time. In fields where the cost of a false alarm is very high – such as medical research or legal decisions – researchers sometimes use a stricter threshold of 99% confidence, reducing the Type 1 error rate to 1%.</p>
</section>
<section id="type-2-error-a-missed-signal" class="level3" data-number="21.5.2">
<h3 data-number="21.5.2" class="anchored" data-anchor-id="type-2-error-a-missed-signal"><span class="header-section-number">21.5.2</span> Type 2 Error: A Missed Signal</h3>
<p>A <strong>Type 2 error</strong> occurs when we fail to reject the null hypothesis even though the alternate hypothesis is actually true. In other words, the training programme <em>did</em> work, but our data did not give us enough evidence to see it.</p>
<p>This is the <em>missed signal</em> error. Something real was happening, but we were not able to detect it.</p>
<p>In our training programme example, a Type 2 error would mean telling the HR director “we found no evidence that the programme works” – and perhaps abandoning a genuinely effective training initiative – when in truth the programme was improving sales all along. We simply did not have a large enough sample, or the improvement was subtle enough, that our test could not pick it up.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick Check
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the training programme example, which error do you think would be more costly to the company: a Type 1 or a Type 2 error? Is there a definitive answer?</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There is no single right answer – it depends on the costs involved. A Type 1 error means wasting money rolling out a useless programme. A Type 2 error means discarding a useful one and missing out on the sales improvement it would have delivered. In most business contexts, both errors are costly, and the right balance depends on how expensive the programme is and how large the potential sales benefit is. This trade-off is a genuine business decision, not just a statistical one.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The two errors, side by side
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Null hypothesis is actually TRUE</th>
<th>Null hypothesis is actually FALSE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>We reject the null</strong></td>
<td>Type 1 Error (false alarm)</td>
<td>Correct decision ✓</td>
</tr>
<tr class="even">
<td><strong>We do not reject the null</strong></td>
<td>Correct decision ✓</td>
<td>Type 2 Error (missed signal)</td>
</tr>
</tbody>
</table>
<p>Notice that we can never observe both errors at the same time – in any given situation, the null hypothesis is either true or false. The errors are possibilities, not certainties.</p>
</div>
</div>
</section>
</section>
<section id="formulating-hypotheses-examples-across-domains" class="level2" data-number="21.6">
<h2 data-number="21.6" class="anchored" data-anchor-id="formulating-hypotheses-examples-across-domains"><span class="header-section-number">21.6</span> Formulating Hypotheses: Examples Across Domains</h2>
<p>Now that we understand the framework through our running example, let us see how it applies across a wide range of situations. In each case, we will state the null and alternate hypotheses and think carefully about what Type 1 and Type 2 errors would mean in practice.</p>
<section id="example-1-a-new-advertising-campaign-business" class="level3" data-number="21.6.1">
<h3 data-number="21.6.1" class="anchored" data-anchor-id="example-1-a-new-advertising-campaign-business"><span class="header-section-number">21.6.1</span> Example 1: A New Advertising Campaign (Business)</h3>
<p>A consumer goods company runs a new digital advertising campaign and wants to know whether it has increased online sales.</p>
<p><strong>Null hypothesis:</strong> The campaign has had no effect on online sales. Average weekly sales are unchanged.</p>
<p><strong>Alternate hypothesis:</strong> The campaign has increased online sales. Average weekly sales are now higher.</p>
<p><strong>Type 1 error:</strong> We conclude the campaign worked and continue spending on it, when in reality the sales increase was just natural fluctuation. The company wastes its advertising budget on an ineffective campaign.</p>
<p><strong>Type 2 error:</strong> We conclude the campaign had no effect and pull the budget, when in reality it was driving real sales growth. The company abandons a profitable marketing channel.</p>
<p><strong>Which is worse?</strong> If the campaign is expensive, a Type 1 error is very costly. But if the potential sales uplift is large, a Type 2 error represents a significant missed opportunity. The marketing team needs to weigh these costs explicitly.</p>
<hr>
</section>
<section id="example-2-quality-control-in-manufacturing-business" class="level3" data-number="21.6.2">
<h3 data-number="21.6.2" class="anchored" data-anchor-id="example-2-quality-control-in-manufacturing-business"><span class="header-section-number">21.6.2</span> Example 2: Quality Control in Manufacturing (Business)</h3>
<p>A factory produces components with a specified average weight of 500 grams. The quality control team periodically samples components from the production line to check whether the machinery has drifted out of calibration.</p>
<p><strong>Null hypothesis:</strong> The machinery is working correctly. The average component weight is 500 grams.</p>
<p><strong>Alternate hypothesis:</strong> The machinery has drifted out of calibration. The average component weight is no longer 500 grams.</p>
<p><strong>Type 1 error:</strong> We conclude the machinery is out of calibration and halt production to recalibrate it, when it was actually working fine. The company incurs unnecessary downtime and recalibration costs.</p>
<p><strong>Type 2 error:</strong> We conclude the machinery is fine and keep running, when it has actually drifted. The factory continues producing defective components, potentially leading to product recalls, customer complaints, and reputational damage.</p>
<p><strong>Which is worse?</strong> In most manufacturing settings, Type 2 errors are far more costly. The consequences of shipping defective products typically far outweigh the cost of an unnecessary recalibration. This is why quality-critical industries often use very sensitive tests, accepting a higher rate of false alarms in exchange for rarely missing a real defect.</p>
<hr>
</section>
<section id="example-3-loan-default-risk-finance" class="level3" data-number="21.6.3">
<h3 data-number="21.6.3" class="anchored" data-anchor-id="example-3-loan-default-risk-finance"><span class="header-section-number">21.6.3</span> Example 3: Loan Default Risk (Finance)</h3>
<p>A bank is developing a model to predict whether a loan applicant will default. For each applicant, the bank must decide: grant the loan or deny it?</p>
<p><strong>Null hypothesis:</strong> The applicant will not default (they are a creditworthy borrower).</p>
<p><strong>Alternate hypothesis:</strong> The applicant will default.</p>
<p><strong>Type 1 error:</strong> The bank predicts the applicant will default and denies the loan, when the applicant would actually have repaid it without problems. The bank loses a profitable customer and the applicant is unfairly denied credit.</p>
<p><strong>Type 2 error:</strong> The bank predicts the applicant will not default and approves the loan, when the applicant actually defaults. The bank loses the loaned money.</p>
<p><strong>Which is worse?</strong> This depends on the bank’s risk appetite and economic conditions. During a financial downturn, banks tend to tighten their lending criteria – effectively accepting more Type 1 errors (rejecting good customers) to minimise Type 2 errors (approving bad ones). During a boom, the balance may shift the other way.</p>
<hr>
</section>
<section id="example-4-a-new-drug-everyday-life-health" class="level3" data-number="21.6.4">
<h3 data-number="21.6.4" class="anchored" data-anchor-id="example-4-a-new-drug-everyday-life-health"><span class="header-section-number">21.6.4</span> Example 4: A New Drug (Everyday Life / Health)</h3>
<p>A pharmaceutical company has developed a new drug to lower blood pressure. Before it can be approved, regulators require clinical trial evidence that it actually works.</p>
<p><strong>Null hypothesis:</strong> The drug has no effect on blood pressure compared to a placebo.</p>
<p><strong>Alternate hypothesis:</strong> The drug lowers blood pressure more than a placebo does.</p>
<p><strong>Type 1 error:</strong> We conclude the drug works and approve it for public use, when in reality it does not work – or worse, has side effects without any benefit. Patients take a useless or harmful drug, and the regulator’s credibility is damaged.</p>
<p><strong>Type 2 error:</strong> We conclude the drug does not work and reject it, when in reality it does lower blood pressure effectively. Patients who could have benefited from it are denied access.</p>
<p><strong>Which is worse?</strong> Drug regulators around the world have historically been more afraid of Type 1 errors – approving harmful drugs – than Type 2 errors. This is why clinical trials for new drugs use very strict significance thresholds and require multiple phases of testing. The tragic cases of drugs approved prematurely and later found to cause harm have shaped this culture of caution.</p>
<hr>
</section>
<section id="example-5-a-sports-performance-claim-sports" class="level3" data-number="21.6.5">
<h3 data-number="21.6.5" class="anchored" data-anchor-id="example-5-a-sports-performance-claim-sports"><span class="header-section-number">21.6.5</span> Example 5: A Sports Performance Claim (Sports)</h3>
<p>A professional football club introduces a new sports science recovery protocol for its players. The head coach claims it reduces muscle recovery time after matches, allowing players to train harder during the week.</p>
<p><strong>Null hypothesis:</strong> The recovery protocol has no effect. Average muscle recovery time is unchanged.</p>
<p><strong>Alternate hypothesis:</strong> The recovery protocol reduces average muscle recovery time.</p>
<p><strong>Type 1 error:</strong> The club concludes the protocol works and invests heavily in it – hiring specialists, restructuring training schedules – when in reality any improvement was just natural variation in player performance. The club wastes resources and disrupts a training routine that was working fine.</p>
<p><strong>Type 2 error:</strong> The club concludes the protocol does not work and abandons it, when it actually does speed up recovery. Players train under more fatigue than necessary, increasing injury risk and reducing match performance.</p>
<p><strong>Which is worse?</strong> In elite sport, where marginal gains can mean the difference between winning and losing a championship, Type 2 errors can be very costly. However, if the intervention is expensive or disrupts the team’s established culture, a Type 1 error also carries real consequences.</p>
<hr>
</section>
<section id="example-6-employee-absenteeism-business-hr" class="level3" data-number="21.6.6">
<h3 data-number="21.6.6" class="anchored" data-anchor-id="example-6-employee-absenteeism-business-hr"><span class="header-section-number">21.6.6</span> Example 6: Employee Absenteeism (Business / HR)</h3>
<p>A company notices that absenteeism rates appear higher in one regional office than in others. HR wants to know whether this is a genuine pattern or just random variation across offices.</p>
<p><strong>Null hypothesis:</strong> There is no real difference in absenteeism rates between this office and the others. The apparent difference is just chance.</p>
<p><strong>Alternate hypothesis:</strong> This office genuinely has a higher absenteeism rate, suggesting an underlying problem (management issues, morale, working conditions, etc.).</p>
<p><strong>Type 1 error:</strong> HR concludes there is a real problem at this office and launches an investigation – disrupting the team, potentially alienating managers – when the higher absenteeism was just statistical noise and there is no real issue. Time and goodwill are wasted.</p>
<p><strong>Type 2 error:</strong> HR concludes the difference is just chance and takes no action, when the office genuinely does have a problem. The underlying issue – poor management, a toxic culture, inadequate facilities – goes unaddressed and worsens over time.</p>
<p><strong>Which is worse?</strong> A Type 2 error here risks long-term damage to employee wellbeing and productivity. Most HR professionals would rather investigate a false alarm than miss a genuine culture problem, suggesting that a lower evidence threshold – and therefore accepting more Type 1 errors – might be appropriate in this context.</p>
<hr>
</section>
<section id="example-7-online-checkout-redesign-business-technology" class="level3" data-number="21.6.7">
<h3 data-number="21.6.7" class="anchored" data-anchor-id="example-7-online-checkout-redesign-business-technology"><span class="header-section-number">21.6.7</span> Example 7: Online Checkout Redesign (Business / Technology)</h3>
<p>An e-commerce company redesigns its checkout page to reduce cart abandonment. The product team runs an A/B test: half of visitors see the old design, half see the new one. The question is whether the new design leads to a meaningfully higher conversion rate.</p>
<p><strong>Null hypothesis:</strong> The new checkout design has no effect on conversion rates. The conversion rate is the same for both designs.</p>
<p><strong>Alternate hypothesis:</strong> The new checkout design produces a higher conversion rate than the old one.</p>
<p><strong>Type 1 error:</strong> The team concludes the new design is better and rolls it out to all users, when the difference in conversion rates was just random noise. Users get a new experience that offers no real benefit, and the engineering effort was wasted.</p>
<p><strong>Type 2 error:</strong> The team concludes the designs perform equally well and keeps the old one, when the new design was genuinely better. Every future customer who abandons the cart is a missed sale that the new design could have prevented.</p>
<p><strong>Which is worse?</strong> In A/B testing, Type 2 errors are often underappreciated. Companies sometimes run tests that are too short or on too small a sample, making them unlikely to detect real improvements. The cost of a Type 2 error here is measured in lost revenue for every day the inferior design remains in place.</p>
<hr>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick Check
</div>
</div>
<div class="callout-body-container callout-body">
<p>For the online checkout A/B test example, how might the company reduce the risk of a Type 2 error without changing its confidence threshold?</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The company could run the test for longer, or expose a larger proportion of its users to the test. Both approaches increase the sample size, which gives the test more statistical power – meaning it is better able to detect a real difference if one exists. In general, larger samples reduce Type 2 errors without requiring any change to the confidence threshold.</p>
</div>
</div>
</div>
</section>
</section>
<section id="a-note-on-what-failing-to-reject-really-means" class="level2" data-number="21.7">
<h2 data-number="21.7" class="anchored" data-anchor-id="a-note-on-what-failing-to-reject-really-means"><span class="header-section-number">21.7</span> A Note on What “Failing to Reject” Really Means</h2>
<p>One of the most common misunderstandings in statistics is equating “we did not find evidence against the null hypothesis” with “the null hypothesis is true.”</p>
<p>These are very different statements.</p>
<p>If our training programme study found no statistically significant improvement in sales, the correct conclusion is: <em>we did not find sufficient evidence to conclude the programme works.</em> It is not: <em>the programme definitely does not work.</em></p>
<p>The absence of evidence is not evidence of absence. Our test might have missed a real effect because our sample was too small, because the effect was subtle, or because there was too much noise in the data. This is exactly the Type 2 error we discussed above.</p>
<p>This distinction matters enormously in business. A manager who hears “the test was not significant” and concludes “the initiative failed” may be making a Type 2 error in their reasoning – discarding something that actually works.</p>
<p>We begin with the coin-toss story from the very start of the previous chapter, because it turns out to be a perfect laboratory for the core ideas. We then move to a production-line quality problem, a staffing experiment, and finally an extended business story set inside a real company.</p>
<hr>
</section>
<section id="sec-coin-toss-example" class="level2" data-number="21.8">
<h2 data-number="21.8" class="anchored" data-anchor-id="sec-coin-toss-example"><span class="header-section-number">21.8</span> Numerical Example: Revisiting our clairvoyant coin-toss guessing friend</h2>
<section id="the-setup" class="level3" data-number="21.8.1">
<h3 data-number="21.8.1" class="anchored" data-anchor-id="the-setup"><span class="header-section-number">21.8.1</span> The Setup</h3>
<p>Recall the opening of the chapter: a friend tells you they can predict the outcome of a coin flip every single time. You are skeptical. So you test them.</p>
<p>Let us now put numbers to this story.</p>
<p><strong>Null hypothesis:</strong> Our friend has no special ability. Each prediction is just a random guess, correct 50% of the time purely by chance.</p>
<p><strong>Alternate hypothesis:</strong> Our friend genuinely can predict coin flips better than chance.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick Check
</div>
</div>
<div class="callout-body-container callout-body">
<p>Why did we formulate the null and alternate hypotheses the way we did?</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The null hypothesis represents the status quo. Unless we have sufficient evidence, we cannot reject it in favor of the alternate hypothesis. In this case, we are very skeptical that anyone can predict coin toss outcomes at anything better than random chance. So that is the null hypothesis.</p>
</div>
</div>
</div>
</section>
<section id="the-logic" class="level3" data-number="21.8.2">
<h3 data-number="21.8.2" class="anchored" data-anchor-id="the-logic"><span class="header-section-number">21.8.2</span> The Logic</h3>
<p>Our approach is going to be the following, We initially assume that the null hypothesis is true — that our friend is just guessing. We then watch the evidence accumulate as they make consecutive predictions. After each prediction, we ask: <em>if the null hypothesis were true, how likely would it be to see a result at least this good purely by chance?</em> When that becomes very small (&lt; 0.05 ), we feel justified in rejecting the null hypothesis and concluding that something other than luck is at work.</p>
<p>If the null hypothesis is true — if our friend is just guessing — then each individual prediction has a 50% chance of being correct. Getting one right by luck is as likely as a fair coin landing heads: one chance in two, or 0.5.</p>
<p>What about getting two in a row right by pure luck? Each flip is independent, so the probability is 0.5 × 0.5 = 0.25, or 25%. Let us say the coin came up {H, T} in the two tries and our friend got them both right. What is the probability of this? Well guessing randomly the firend could have guessed {H, H}, {H, T}, {T, H}, or {T, T} with equal probability. Only one of those four possibilities would have been correct, so the probability of getting two in a row right by chance is 1 in 4, or 25%.</p>
<p>Every additional correct prediction cuts the probability in half, because our friend would need <em>another</em> lucky guess on top of all the previous ones.</p>
<p>The key question we ask after each flip is: <em>if our friend were just guessing, how likely is it that they would have done at least this well purely by chance?</em></p>
</section>
<section id="watching-the-evidence-accumulate" class="level3" data-number="21.8.3">
<h3 data-number="21.8.3" class="anchored" data-anchor-id="watching-the-evidence-accumulate"><span class="header-section-number">21.8.3</span> Watching the Evidence Accumulate</h3>
<p>We keep tossing the coin and watching our friend predict. After each prediction, we update our calculation of how likely it is that they are just guessing.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Consecutive correct predictions</th>
<th style="text-align: center;">Probability of doing this well by luck alone</th>
<th style="text-align: center;">Do we reject the null hypothesis?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">50.0%</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">25.0%</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">12.5%</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">6.25%</td>
<td style="text-align: center;">No</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>5</strong></td>
<td style="text-align: center;"><strong>3.125%</strong></td>
<td style="text-align: center;"><strong>Yes</strong> ✓</td>
</tr>
</tbody>
</table>
<p>After the <strong>fifth</strong> consecutive correct prediction, the probability that our friend achieved this purely by chance has fallen to 3.125% — below our 5% threshold (or, 95% confidence. At this point the result is statistically significant at the 95% confidence level. We reject the null hypothesis and are forced to conclude that something other than luck appears to be at work.</p>
</section>
<section id="what-this-tells-us" class="level3" data-number="21.8.4">
<h3 data-number="21.8.4" class="anchored" data-anchor-id="what-this-tells-us"><span class="header-section-number">21.8.4</span> What This Tells Us</h3>
<p>Notice what happened along the way. After four correct predictions the probability was 6.25% — uncomfortably close to the threshold but not quite there. We were not yet willing to abandon our skepticism. The fifth prediction was the tipping point.</p>
<p>Notice also what we are <em>not</em> saying. Rejecting the null hypothesis does not prove our friend has supernatural powers. It says only that the result we observed is too unlikely to dismiss as coincidence at our chosen threshold. What the explanation actually is — a pattern they have spotted, a tell in how we flip the coin, extraordinary luck — is a separate question that statistics alone cannot answer.</p>
<p>This is an intuitive illustration of what hypothesis testing always does: it tells you whether the evidence is strong enough to act on. It does not tell you <em>why</em>.</p>
<p>We deliberately chose the simple case of a coin toss to illustrate the concepts clearly. We can calculate the probabilities easily. The evidence accumulates in a satisfying and transparent way, and the moment of rejection is clear.</p>
<p>But real business problems are rarely this clean. We have messier data and less obvious distributions, and face considerably higher stakes than settling an argument with a friend.</p>
<p>In the next chapter we will use the same logic: - assume initially that the null hypothesis is true - gather data - calculate how likely the observed result would be by chance - reject the null hypothesis if that probability falls below 5%,</p>
<p>and apply it to three realistic problems drawn from operations, quality control, and digital product management.</p>
<p>We will face slightly more involved mechanics, but the underlying question is always identical to the one we asked here: is this result too unlikely to be a coincidence?</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Quick Check
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we used a stricter threshold of 99% confidence — meaning we would only reject the null hypothesis if the probability of the result arising by luck fell below 1%. How many consecutive correct predictions would our friend need before we rejected the null hypothesis?</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Suggested answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We need to find how many correct predictions <span class="math inline">\(n\)</span> are needed so that <span class="math inline">\((0.5)^n &lt; 0.01\)</span>. After six correct predictions the probability is <span class="math inline">\((0.5)^6 = 1.5625\%\)</span>, which is still above 1%. After seven correct predictions the probability falls to <span class="math inline">\((0.5)^7 \approx 0.78\%\)</span>, which is below 1%. So at the 99% confidence level, our friend would need <strong>seven</strong> consecutive correct predictions. Tougher standards demand stronger evidence.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Summary: Key ideas from this chapter
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Hypothesis testing is a formal framework for deciding whether data provide sufficient evidence to believe a claim.</li>
<li>We always start with a <strong>null hypothesis</strong> (the status quo, assumed true by default) and an <strong>alternate hypothesis</strong> (the interesting claim we are looking for evidence to support).</li>
<li>We reject the null hypothesis only when the evidence against it is strong enough – conventionally, when we have at least 95% confidence, meaning there is less than a 5% chance we are making a mistake.</li>
<li>A <strong>Type 1 error</strong> (false alarm) occurs when we reject a null hypothesis that is actually true. The 5% confidence threshold directly controls how often this can happen.</li>
<li>A <strong>Type 2 error</strong> (missed signal) occurs when we fail to reject a null hypothesis that is actually false. Larger samples reduce the risk of Type 2 errors.</li>
<li>The relative costs of Type 1 and Type 2 errors depend on context. Deciding which error is more tolerable is a business and ethical judgment, not just a statistical one.</li>
<li>Failing to find evidence against the null hypothesis does not prove the null hypothesis is true – it may simply mean our test was not powerful enough to detect the effect.</li>
</ol>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../modules/07-probability/probability-distributions.html" class="pagination-link" aria-label="Probability Distributions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Probability Distributions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>