{
  "hash": "e729cd1e3d5ceeffd9a7bef3e089d91b",
  "result": {
    "engine": "knitr",
    "markdown": "# Visualizing Mean Models {#sec-visualizing-mean-models}\n\nIn the prior chapters, we have established the overall *mean* as the *best model* when we have no other *explanatory* variable, and the category mean as the *simplest*best model\\* when we have a categorical explanatory variable.\n\nIn this chapter we use the *point_plot* function to visualize these models.\n\n## Business scenario -- fuel efficiency of vehicle fleet\n\nIn @sec-mean-model, we used a set of numbers to play a game. Now we will extend the idea to actual data frames.\n\nYou manage a company that operates a fleet of rental cars used primarily for city driving. The fleet includes a wide range of vehicles, from compact sedans to larger SUVs, each with different city fuel efficiency.\n\nFor planning purposes, the company must commit to one single number to represent the expected city fuel efficiency of a car drawn at random from the fleet. This number is used repeatedly—for estimating fuel costs, setting reimbursement rates, and budgeting operating expenses.\n\nThe company does not know in advance which specific car will be rented on a given day. Some days the car will be more fuel-efficient than expected, and on other days less fuel-efficient.\n\nIf the company assumes fuel efficiency that is too high, it underestimates fuel costs. If it assumes fuel efficiency that is too low, it overestimates costs and ties up capital unnecessarily. Larger errors in either direction are more costly than smaller ones.\n\nThe decision is not evaluated based on a single rental. Instead, it is judged by how well it performs across many rentals over time.\n\nIn this setting, the question becomes: \"What single number should the company commit to so that total long-run cost is as small as possible?\"\n\nThe data about your fleet is in the *mpg* data. It has many variables, but we focus here on the variable *cty* showing us the city miles per gallon of each car.\n\nAssuming (artificially) that the company is only allowed to use the variable *cty* what single number should they commit to?\n\n### Committing to one number for the entire fleet\n\nBased on our discussion in @sec-mean-model, we know that the the company should commit to the average of the variable *cty*. We can compute the average using the *summarize* and *mean* functions as the code below shows.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  summarize(avg_cty = mean(cty))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 x 1\n  avg_cty\n    <dbl>\n1    16.9\n```\n\n\n:::\n:::\n\n\nWe can also visualize it thus:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  point_plot(cty ~ 1,\n             annot = \"model\",\n             interval = \"none\")\n```\n:::\n\n\n<!-- TODO: Add figure of above plot after fixing package -->\n\nThis generates @fig-cty-simple-mean-model.\n\n![Visualizing mean *cty* as the model](../../images/fig-cty-simple-mean-model.png){#fig-cty-simple-mean-model width=\"70%\" fig-align=\"center\"}\n\nThe model shows the scatter plot of the points as well as a line. This line represents the model. You can see that it falls exactly at the average of the *cty* values.\n\nTake a look at the code:\n\nThe tilde expression\n\n```         \ncty ~ 1\n```\n\nin the code sets *cty* ans=d the response variable and, by placing 1 on the RHS, shows that we have no explanatory variables.\n\nThe part\n\n```         \nannot = \"model\n```\n\nCauses a *model* to be visualized as well. We know that the mean is our model and this plot visualizes it by drawing a line at the average *cty*.\n\nFor now, you can ignore:\n\n```         \ninterval = \"none\"\n```\n\nSo, if we have to commit to one number as our estimate for the city mileage irrespective of other details about a car like its *class*, *drv* or anything else, our best commitment is to the overall average. As we have seen in @sec-models-intro, this is a model with just a response variable and no explanatory variables. We can write it as @eq-cty-model.\n\n$$\n\\widehat{\\text{cty}} = 16.9\n$$ {#eq-cty-model}\n\nWe placed a *hat* on *cty* because this is just an estimate or a model value and not an actual data point.\n\n## We can do better with more information\n\nInstead of having to commit to one single number for the fuel efficiency for the entire fleet, what if we could use a different number for each class of vehicle? In out *mpg* data set, we have vehicles of different classes -- variable *class*. This has values like *Compact*, *SUV* and *Pickup truck*.\n\nBased on @sec-category-means, we know that for each class of vehicle, we should commit to the average of *cty* for that class.\n\nWe can compute these averages easily:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  summarize(avg_cty = mean(cty), .by = class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 x 2\n  class      avg_cty\n  <chr>        <dbl>\n1 compact       20.1\n2 midsize       18.8\n3 suv           13.5\n4 2seater       15.4\n5 minivan       15.8\n6 pickup        13  \n7 subcompact    20.4\n```\n\n\n:::\n:::\n\n\nNote how the above code is very similar to what we would use for computing the overall average, but we have added:\n\n```         \n.by = class\n```\n\nTo show that we do not want just one average for the whole data frame, but we want separate averages for each *class* of vehicle. As simple as that!\n\nLet us visualize this model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  point_plot(cty ~ class, annot = \"model\",\n             interval = \"none\")\n```\n:::\n\n\n@fig-cty-class-model shows the model visualization.\n\n![Visualizing the more sophisticated model of mean *cty* by *class* as the model when we have *class* as an explanatory variable](../../images/fig-cty-class-model.png){#fig-cty-class-model width=\"70%\" fig-align=\"center\"}\n\nHow do we express this model as an equation like we did with @eq-cty-model?\n\n@eq-cty-class-model shows the model as an equation.\n\n$$\n\\widehat{\\text{cty}} =\n\\begin{cases}\n20.1 & \\text{if } \\text{class} = \\text{\"compact\"} \\\\\n18.8 & \\text{if } \\text{class} = \\text{\"midsize\"} \\\\\n13.5 & \\text{if } \\text{class} = \\text{\"SUV\"} \\\\\n15.4 & \\text{if } \\text{class} = \\text{\"2seater\"} \\\\\n15.8 & \\text{if } \\text{class} = \\text{\"minivan\"} \\\\\n13.0 & \\text{if } \\text{class} = \\text{\"pickup\"} \\\\\n20.4 & \\text{if } \\text{class} = \\text{\"subcompact\"}\n\\end{cases}\n$$ {#eq-cty-class-model}\n\nInstead of class, we can have *drv* as the explanatory variable as well. Here are code snippets that will compute the model and plot it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  summarize(avg_cty = mean(cty), .by = drv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 x 2\n  drv   avg_cty\n  <chr>   <dbl>\n1 f        20.0\n2 4        14.3\n3 r        14.1\n```\n\n\n:::\n:::\n\n\nNote that we only had to change the .by to reflect that we are now computing averages by *drv*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpg |> \n  point_plot(cty ~ drv, annot = \"model\",\n             interval = \"none\")\n```\n:::\n\n\nWe just changed the RHS of the tilde expression to *drv* instead of *class*.\n\n@fig-cty-drv-model shows the visualization.\n\n![Visualizing the model of mean *cty* by *drv* as the model when we have *drv* as an explanatory variable](../../images/fig-cty-drv-model.png){#fig-cty-drv-model width=\"70%\" fig-align=\"center\"}\n\n@eq-cty-drv-model shows the model in equation form.\n\n$$\n\\widehat{\\text{cty}} =\n\\begin{cases}\n20.0 & \\text{if } \\text{drv} = \\text{\"f\"} \\\\\n14.3 & \\text{if } \\text{drv} = \\text{\"4\"} \\\\\n14.1 & \\text{if } \\text{drv} = \\text{\"r\"} \\\\\n\\end{cases}\n$$ {#eq-cty-drv-model}\n\nThe *mpg* data frame has another column *fl* to represent the fuel type of the vehicle. We now want to use *fl* as the explanatory variable. Try out the following using the above as examples.\n\n-   Write R code to compute the average of *cty* for each fuel type\n-   Write R code to visualize the model with *cty* as the response variable and *fl* as the explanatory variable.\n-   Write out the model equation for this scenario.\n",
    "supporting": [
      "visualizing-simple-models_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}