<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Exploring Relationships through Scatterplots – Introduction to Business Statistics: A Modeling Approach</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../modules/02-variability/02-overview.html" rel="next">
<link href="../../modules/01-data-visualization/data-frames.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-950d71faa9ec5383cefc3735863c97d1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script>


<link rel="stylesheet" href="../../custom.scss">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../modules/01-data-visualization/01-overview.html">Data, Visualization, and Patterns</a></li><li class="breadcrumb-item"><a href="../../modules/01-data-visualization/point-plots.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploring Relationships through Scatterplots</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Introduction to Business Statistics: A Modeling Approach</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Business Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data, Visualization, and Patterns</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/01-data-visualization/01-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 1: Data, Visualization &amp; Patterns</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/01-data-visualization/data-frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Frames and Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/01-data-visualization/point-plots.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploring Relationships through Scatterplots</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Variation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/02-variability/02-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 2: Variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/02-variability/violin-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Using Violin Plots to Visualize Distribution</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/02-variability/variance-and-sd.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Variance and standard deviation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction to models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/03-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Module 3: Introduction to models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Simplest Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/category-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Category Means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/03-introduction-to-models/residuals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Residuals</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">More on models – least squares</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/04-more-on-models/04-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4: More on Models – Least Squares</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/04-more-on-models/model-concept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Concept of model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Linear Regression Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/05-regression-no-ci/05-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 4: Linear Regression Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/05-regression-no-ci/line-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Line Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/05-regression-no-ci/interpreting-coefficients.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Interpreting coefficients</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Explanatory Power of a Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/06-variance-analysis/06-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 6: Explanatory Power of a Model</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Populations, Samples and Inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/07-populations-samples/07-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 7: Population, Samples and Inference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/07-populations-samples/pop-vs-sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Population vs Sample</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/07-populations-samples/sampling-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Sampling Variability</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true">
 <span class="menu-text">Probability as Variation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/08-probability-variation/08-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 8: Probability as Variation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/08-probability-variation/randomness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Randomness</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/08-probability-variation/variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Variability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/08-probability-variation/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true">
 <span class="menu-text">Sampling Variation and Estimators</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/09-sampling-variation/09-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 9: Sampling Variation and Estimators</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/09-sampling-variation/se-estimators.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">SE Estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/09-sampling-variation/sampling-dist-slopes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Sampling Distributions Slopes</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true">
 <span class="menu-text">Confidence Intervals and Bands</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/10-confidence-bands/10-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 10: Confidence Intervals and Bands</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/10-confidence-bands/ci-slope.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">CI Slope</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/10-confidence-bands/ci-bands.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">CI Bands</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true">
 <span class="menu-text">Signal, Noise, and R-Squared</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/11-signal-noise/11-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 11: Signal and Noise</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/11-signal-noise/variance-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Variance Decomposition</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/11-signal-noise/r-squared.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">R-Squared</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true">
 <span class="menu-text">Hypothesis Testing via Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/12-hypothesis-testing/12-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 12: Hypothesis Testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/12-hypothesis-testing/t-tests-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">t-tests for Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/12-hypothesis-testing/interpretation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Interpretation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true">
 <span class="menu-text">Business Applications of Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/13-business-applications/13-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 13: Business Applications</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/13-business-applications/marketing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Marketing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/13-business-applications/finance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Finance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/13-business-applications/hr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Human Resources</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/13-business-applications/operations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Operations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true">
 <span class="menu-text">Projects and Datasets</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/14-projects/14-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Module 14: Projects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/14-projects/project-guidelines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Project Guidelines</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/14-projects/datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Datasets</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../modules/Appendices/01-overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Appendices</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link active" data-scroll-target="#learning-outcomes"><span class="header-section-number">2.1</span> Learning outcomes</a></li>
  <li><a href="#plotting-the-relationship-between-two-numerical-variables" id="toc-plotting-the-relationship-between-two-numerical-variables" class="nav-link" data-scroll-target="#plotting-the-relationship-between-two-numerical-variables"><span class="header-section-number">2.2</span> Plotting the relationship between two numerical variables</a>
  <ul class="collapse">
  <li><a href="#finding-the-point-corresponding-to-a-row-of-the-data-frame" id="toc-finding-the-point-corresponding-to-a-row-of-the-data-frame" class="nav-link" data-scroll-target="#finding-the-point-corresponding-to-a-row-of-the-data-frame"><span class="header-section-number">2.2.1</span> Finding the point corresponding to a row of the data frame</a></li>
  <li><a href="#finding-the-price-and-sales_qty-corresponding-to-a-point-on-the-plot" id="toc-finding-the-price-and-sales_qty-corresponding-to-a-point-on-the-plot" class="nav-link" data-scroll-target="#finding-the-price-and-sales_qty-corresponding-to-a-point-on-the-plot"><span class="header-section-number">2.2.2</span> Finding the <em>price</em> and <em>sales_qty</em> corresponding to a point on the plot</a></li>
  <li><a href="#dissecting-the-code" id="toc-dissecting-the-code" class="nav-link" data-scroll-target="#dissecting-the-code"><span class="header-section-number">2.2.3</span> Dissecting the code</a></li>
  <li><a href="#interpreting-the-plot" id="toc-interpreting-the-plot" class="nav-link" data-scroll-target="#interpreting-the-plot"><span class="header-section-number">2.2.4</span> Interpreting the plot</a></li>
  <li><a href="#positive-and-negative-relationships" id="toc-positive-and-negative-relationships" class="nav-link" data-scroll-target="#positive-and-negative-relationships"><span class="header-section-number">2.2.5</span> Positive and negative relationships</a></li>
  <li><a href="#putting-a-number-on-the-relationship-the-correlation-coefficient" id="toc-putting-a-number-on-the-relationship-the-correlation-coefficient" class="nav-link" data-scroll-target="#putting-a-number-on-the-relationship-the-correlation-coefficient"><span class="header-section-number">2.2.6</span> Putting a number on the relationship: The correlation coefficient</a></li>
  <li><a href="#perfect-correlation" id="toc-perfect-correlation" class="nav-link" data-scroll-target="#perfect-correlation"><span class="header-section-number">2.2.7</span> Perfect correlation</a></li>
  <li><a href="#how-the-point-cloud-looks-for-various-correlation-coefficients" id="toc-how-the-point-cloud-looks-for-various-correlation-coefficients" class="nav-link" data-scroll-target="#how-the-point-cloud-looks-for-various-correlation-coefficients"><span class="header-section-number">2.2.8</span> How the point cloud looks for various correlation coefficients</a></li>
  </ul></li>
  <li><a href="#plotting-a-numerical-variable-against-a-categorical-one" id="toc-plotting-a-numerical-variable-against-a-categorical-one" class="nav-link" data-scroll-target="#plotting-a-numerical-variable-against-a-categorical-one"><span class="header-section-number">2.3</span> Plotting a numerical variable against a categorical one</a>
  <ul class="collapse">
  <li><a href="#point_plot-and-jittering" id="toc-point_plot-and-jittering" class="nav-link" data-scroll-target="#point_plot-and-jittering"><span class="header-section-number">2.3.1</span> <em>point_plot</em> and “jittering”</a></li>
  </ul></li>
  <li><a href="#bringing-a-third-variable-into-the-plot" id="toc-bringing-a-third-variable-into-the-plot" class="nav-link" data-scroll-target="#bringing-a-third-variable-into-the-plot"><span class="header-section-number">2.4</span> Bringing a third variable into the plot</a>
  <ul class="collapse">
  <li><a href="#understanding-the-tilde-expression-to-add-a-third-variable" id="toc-understanding-the-tilde-expression-to-add-a-third-variable" class="nav-link" data-scroll-target="#understanding-the-tilde-expression-to-add-a-third-variable"><span class="header-section-number">2.4.1</span> Understanding the tilde expression to add a third variable</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../modules/01-data-visualization/01-overview.html">Data, Visualization, and Patterns</a></li><li class="breadcrumb-item"><a href="../../modules/01-data-visualization/point-plots.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploring Relationships through Scatterplots</span></a></li></ol></nav>
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Exploring Relationships through Scatterplots</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The term <em>statistics</em> often conjures up thoughts of numerical computations. However, before we perform various co mputations, we often get a feel for the data and the underlying patterns by first visualizing the data. In this course we will use only a few standard plots to communicate essential statistical ideas.</p>
<p>In fact, use a single function – <em>point_plot</em> – to generate all of our plots. Although R offers numerous, sophisticated plotting features to plot almost anything we can imagine, we will keep things simple and focus only on what we need to support the concepts that our course covers.</p>
<section id="learning-outcomes" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="learning-outcomes"><span class="header-section-number">2.1</span> Learning outcomes</h2>
<p>After working though this chapter, you will be able to:</p>
<ul>
<li><p>given a scatterplot of two numeric variables with the plot’s axes labeled explain precisely what determines the location of a given point</p></li>
<li><p>given a scatterplot of two numeric variables, the data frame on which it is based, and a specific point on the plot, identify the corresponding row in the data frame</p></li>
<li><p>given a scatterplot of two numeric variables, the data frame on which it is based, and a specific row in the data frame, identify the corresponding point on the plot</p></li>
<li><p>given a scatterplot one numeric variable on the y-axis against a categorical variable on the x-axis, explain how many different values exist for the x-axis</p></li>
<li><p>given a scatterplot one numeric variable on the y-axis against a categorical variable on the x-axis, explain the speific appearance of the points along the x-axis for each of the category levels</p></li>
<li><p>describe a tilde-expression (a model expression)</p></li>
<li><p>given a tilde-expression with one variable on eithert side of the tilde, state how they relate to the plot axes</p></li>
<li><p>given a tidle expression with two variables on the right of the tilde, expalin the mnappings of the elements of the tidle expression to the elements of the plot</p></li>
<li><p>given a tidle expression with two variablkes on the right of the tilde, expalin the mnappings of the elements of the tidle expression to the elements of the plot</p></li>
<li><p>explain why the points are jittered along the x-axis when the x-axis has a categorical variable</p></li>
<li><p>Given a scatterplot of a num eric variable on the y-axis and a caregorical variable on the y-axis, identify a pair of points that would have overlapped if not for jittering</p></li>
<li><p>use the point_plot function to</p>
<ul>
<li><p>generate a scatterplot of two numeric variables</p></li>
<li><p>generate a scatterplot of one numeric variable on the y-axis against a categorical variable on the x-axis</p></li>
<li><p>generate ascatterplot of numeric variables on both axes with the points colored based on a third variable</p></li>
<li><p>generate ascatterplot of numeric variables on both axes with the points colored based on a third variable and the plots split into facets based on a fourth variable</p></li>
</ul></li>
</ul>
</section>
<section id="plotting-the-relationship-between-two-numerical-variables" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="plotting-the-relationship-between-two-numerical-variables"><span class="header-section-number">2.2</span> Plotting the relationship between two numerical variables</h2>
<p>The <em>point_plot()</em> function that we will rely on for plots in this course lives in the <em>LSTbook</em> package. We will be using the <em>LSTextra</em>s package. Once we load the <em>LSTextras</em> package (which in turn loads the <em>LSTbook</em> package and all its dependencies), the <em>point_plot()</em> function becomes available for us to use.</p>
<p>Let us first look at the <em>price_demand</em> data frame that is built into the <em>LSTbook</em> package.</p>
<p>A hypothetical company has gathered data for a single product. Over time, and across very similar sales areas, the company has charged different prices for the same product, It has recorded the monthly sales for each price. The dataset <em>price_demand</em> contains the price and the corresponding sales quantities. We would like to study if the two variables <em>price</em> and <em>sales_qty</em> are related in any way.</p>
<p>First let us see some rows from the dataset.</p>
<div class="cell">
<div id="tbl-price-demand" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-price-demand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: Price Demand data (first 15 rows)
</figcaption>
<div aria-describedby="tbl-price-demand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">price</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sales_qty</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">11.8</td>
<td style="text-align: right;">1260</td>
</tr>
<tr class="even">
<td style="text-align: right;">12.1</td>
<td style="text-align: right;">1215</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13.6</td>
<td style="text-align: right;">1214</td>
</tr>
<tr class="even">
<td style="text-align: right;">12.3</td>
<td style="text-align: right;">1298</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12.4</td>
<td style="text-align: right;">1160</td>
</tr>
<tr class="even">
<td style="text-align: right;">13.7</td>
<td style="text-align: right;">1138</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12.6</td>
<td style="text-align: right;">1174</td>
</tr>
<tr class="even">
<td style="text-align: right;">11.2</td>
<td style="text-align: right;">1220</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11.7</td>
<td style="text-align: right;">1313</td>
</tr>
<tr class="even">
<td style="text-align: right;">11.9</td>
<td style="text-align: right;">1283</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13.3</td>
<td style="text-align: right;">1170</td>
</tr>
<tr class="even">
<td style="text-align: right;">12.6</td>
<td style="text-align: right;">1247</td>
</tr>
<tr class="odd">
<td style="text-align: right;">12.6</td>
<td style="text-align: right;">1283</td>
</tr>
<tr class="even">
<td style="text-align: right;">12.3</td>
<td style="text-align: right;">1263</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11.8</td>
<td style="text-align: right;">1259</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The full dataset has 500 rows. With so many rows, we cannot easily get a handle on the overall pattern by looking at the data directly. Visualizing the data might help us. We will do several things in this section: - generate the plot using R code - understand how each element of the plot is related to the original dataset - understand the various elements of the code so that you can use similar code to generate plots that you many need - interpret the plot</p>
<p>The code and the plot appear below. For now, ignore the code. We will discuss it in detail after analyzing the plot itself.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>price_demand <span class="sc">|&gt;</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(sales_qty <span class="sc">~</span> price)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-price-demand" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-price-demand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="point-plots_files/figure-html/fig-price-demand-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-price-demand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.1: Price demand relationship
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-price-demand" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> shows the relationship between <em>price</em> and <em>sales_qty</em> – the two variables in the data frame. Note the following about the plot:</p>
<ul>
<li>The plot has two axes – the x-axis along the width and the y-axis along tbe height.</li>
<li>The plot shows thge values of price on the x-axis and the values of sales_qty on the y-axis.</li>
<li>If you take any single point on the plot, you can drop a vertical line from the point to the x-axis and the point where it intersects the x-axis is the <em>price</em> corresponding to the point.</li>
<li>Similarly, if you draw a horizontal line from the point to intersect the y-axis, you get the <em>sales_qty</em> corresponding to that point.</li>
<li>Each point of the plot corresponds to one row of the dataset. So how many points are on the plot? 500, since the dataset has 500 rows.</li>
<li>Thus given a point on the plot, we should be able to identify a corresponding row of the data frame</li>
<li>Given a row of the data frame, we should be able to identify a corresponding point on the plot.</li>
</ul>
<section id="finding-the-point-corresponding-to-a-row-of-the-data-frame" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="finding-the-point-corresponding-to-a-row-of-the-data-frame"><span class="header-section-number">2.2.1</span> Finding the point corresponding to a row of the data frame</h3>
<p>Let us now try to find the point on the plot corrresponding to the first row in <a href="#fig-price-demand" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>.</p>
<p>The first row of the data frame has <em>price = 11.8</em> and <em>sales_qty = 1260</em>. Therefore, we can find the point by drawing a vertical line from 11.8 on the x-axis to intersect a horizontal line from 1260 on the y-axis. <a href="#fig-first-row-price-demand-on-plot" class="quarto-xref">Figure&nbsp;<span>2.2</span></a> illustrates this. We have highlighted the point by enlarging it.</p>
<div id="fig-first-row-price-demand-on-plot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-first-row-price-demand-on-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-first-row-price-demand-on-plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-first-row-price-demand-on-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.2: Finding the first row of the <em>price_demand</em> data frame on the plot: <em>price = 11.8</em>, <em>sales_qty = 1260</em>
</figcaption>
</figure>
</div>
<p>Similarly, let us locate the point corresponding to row 11 (<em>price = 13.3</em>, <em>sales_qty = 1170</em>).</p>
<p>following the same approach we arrive at <a href="#fig-eleventh-row-price-demand-on-plot" class="quarto-xref">Figure&nbsp;<span>2.3</span></a>.</p>
<div id="fig-eleventh-row-price-demand-on-plot" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-eleventh-row-price-demand-on-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-eleventh-row-price-demand-on-plot.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-eleventh-row-price-demand-on-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.3: Finding the eleventh row of the <em>price_demand</em> data frame on the plot: <em>price = 13.3</em>, <em>sales_qty = 1170</em>
</figcaption>
</figure>
</div>
</section>
<section id="finding-the-price-and-sales_qty-corresponding-to-a-point-on-the-plot" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="finding-the-price-and-sales_qty-corresponding-to-a-point-on-the-plot"><span class="header-section-number">2.2.2</span> Finding the <em>price</em> and <em>sales_qty</em> corresponding to a point on the plot</h3>
<p>We can reverse the above process to find the variable values (and hence the actual row) corresponding to a point on the plot. We will simply drop a vertical line from the point down to the x-axis to get the <em>price</em> and draw a horizontal line from the point to the y-axis to determine the <em>sales_qty</em>. The figure will look similar to the prior two figures.</p>
</section>
<section id="dissecting-the-code" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="dissecting-the-code"><span class="header-section-number">2.2.3</span> Dissecting the code</h3>
<p><a href="#fig-first-point-plot-code" class="quarto-xref">Figure&nbsp;<span>2.4</span></a> decodes the various elements of the code that we used to generate out first point plot in <a href="#fig-price-demand" class="quarto-xref">Figure&nbsp;<span>2.1</span></a>. We see that we pass the data frame <em>price_demand</em> to the <em>point_plot</em> function through the <em>pipe</em> operator. We add the tilde expression for the plot as an additional argument.</p>
<p><a href="#fig-basic-tilde-expression" class="quarto-xref">Figure&nbsp;<span>2.5</span></a> shows us that the <em>point_plot</em> function maps the variable on the left of the tilde operator to the y-axis of the plot and maps the variable to the right of the tilde expression to the x-axis of the plot.</p>
<div id="fig-first-point-plot-code" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-first-point-plot-code-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-first-point-plot-code.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-first-point-plot-code-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.4: Passing the <em>price_demand</em> data frame as argument to the <em>point_plot</em> function through the pipe operator
</figcaption>
</figure>
</div>
<div id="fig-basic-tilde-expression" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-basic-tilde-expression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-basic-tilde-expression.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-basic-tilde-expression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.5: Using a tilde expression to map variables to the axes
</figcaption>
</figure>
</div>
</section>
<section id="interpreting-the-plot" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4" class="anchored" data-anchor-id="interpreting-the-plot"><span class="header-section-number">2.2.4</span> Interpreting the plot</h3>
<p><a href="#fig-price-demand-2" class="quarto-xref">Figure&nbsp;<span>2.6</span></a> repeats the plot of <em>price</em> versus <em>sales_qty</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>price_demand <span class="sc">|&gt;</span> </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(sales_qty <span class="sc">~</span> price)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-price-demand-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-price-demand-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="point-plots_files/figure-html/fig-price-demand-2-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-price-demand-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.6: Price demand relationship (again)
</figcaption>
</figure>
</div>
</div>
</div>
<p>We can see a clear trend showing that, in general, higher prices correspond to lower values of sales quantity.</p>
<p>To be sure, this is only a trend and not a strict rule. That is, given any two points, we do not have a guarantee that the point with the higher price will always have a lower sales quantity. However, this will be true for most of the pairs of points. <a href="#fig-scatter-with-line-segments-1" class="quarto-xref">Figure&nbsp;<span>2.7</span></a> illustrates this with some randomly selected pairs of points. We see that most of the lines point down and to the right – meaning that for most pairs of points, the one with higher <em>price</em> has a lower <em>sales_qty</em>. However, we also see a few examples where the opposite is true.</p>
<p>This is why we only calls this a <em>trend</em> and not a strict rule about the relationship between price and sales_qty.</p>
<div id="fig-scatter-with-line-segments-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-with-line-segments-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-scatter-with-line-segments-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-with-line-segments-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.7: Line segments connecting some pairs of points showing that for most pairs of points the point with higher price has lower sales_qty
</figcaption>
</figure>
</div>
</section>
<section id="positive-and-negative-relationships" class="level3" data-number="2.2.5">
<h3 data-number="2.2.5" class="anchored" data-anchor-id="positive-and-negative-relationships"><span class="header-section-number">2.2.5</span> Positive and negative relationships</h3>
<p>In general, when we discuss the relationship between two numerical variables, if the general trend is that higher values of one correspond to higher values of the other, then we have a positive relationship. On the other hand, is higher values of one variable correspond to lower values of the other then we have a negative relationship.</p>
<p>What kind of relationship does <a href="#fig-price-demand-2" class="quarto-xref">Figure&nbsp;<span>2.6</span></a> show – positive or negative?</p>
<p>You got it right if you said <em>negative</em> – higher values of <em>price</em> correspond to lower values of <em>sales_qty</em>.</p>
<p><a href="#fig-advertising-sales-channel-1" class="quarto-xref">Figure&nbsp;<span>2.8</span></a> shows two positively correlated variables. Here, higher values of one variable are generally related to higher values of the other. We used the <em>advertising_sales_channel</em> data frame for this plot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>advertising_sales_channel <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(weekly_sales_k <span class="sc">~</span> advertising_spend_k)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-advertising-sales-channel-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-advertising-sales-channel-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="point-plots_files/figure-html/fig-advertising-sales-channel-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-advertising-sales-channel-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.8: Weekly sales and advertising spend have a positive relationship – higher advertising generally has higher weekly sales
</figcaption>
</figure>
</div>
</div>
</div>
<p>The data frame <em>returns_dpo</em> contains hypothetical data on various firms’ daily stock returns and the number of days they take to pay their suppliers. <a href="#fig-returns-dpo-1" class="quarto-xref">Figure&nbsp;<span>2.9</span></a> shows the relationship between these variables. We cannot spot any trend. Higher or lower values of one variable do not indicate higher or lower values of the other. Hence there is neither a positive relationship nor a negative one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>returns_dpo <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(daily_return <span class="sc">~</span> dpo)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-returns-dpo-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-returns-dpo-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="point-plots_files/figure-html/fig-returns-dpo-1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-returns-dpo-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.9: Days payment outstanding (dpo) does not have a relationship to the daily stock return
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="putting-a-number-on-the-relationship-the-correlation-coefficient" class="level3" data-number="2.2.6">
<h3 data-number="2.2.6" class="anchored" data-anchor-id="putting-a-number-on-the-relationship-the-correlation-coefficient"><span class="header-section-number">2.2.6</span> Putting a number on the relationship: The correlation coefficient</h3>
<p>Thus far, we have been talking about relationships between variables. Exact sciences like mathematics and statistics like to be precise and assign numbers where possible. Statistics commonly uses the <em>correlation coefficient</em> to quantify the relationship between two numerical variables. This section just introduces the <em>correlation coefficient</em> and shows you how to compute it using R. We will get into the mechanics of the actual computation later in the book.</p>
<p>The correlation coefficient can take a value between -1 and +1. A value of 0 signifies a complete absence of relationship. -1 signifies a perfect negative correlation and +1 signifies a perfact positive correlation. We discuss these ideas below.</p>
<p>We look at some examples now. Revisiting the <em>price_demand</em> data frame, let us use R to compute the correlation coefficient between the variables <em>price</em> and <em>sales_qty</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>price_demand <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">price_sales_qty_correlation =</span> <span class="fu">cor</span>(price, sales_qty))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["price_sales_qty_correlation"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"-0.752"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>We are computing a summary and hence use the <em>summarize</em> function (see <a href="data-frames.html#sec-summarize-function" class="quarto-xref"><span>Section 1.7.6</span></a>). Since the summary we are computing now is the correlation coefficient, we use the <em>cor</em> function within the <em>summarize</em> function. We have chosen to call the comoputed result <em>price_sales_qty_correlation</em>. We could have named it anything we wanted, but chose the sensible approach of giving it a meaningul name.</p>
<p><a href="#fig-price-demand" class="quarto-xref">Figure&nbsp;<span>2.1</span></a> had already shown us the negative relationship between <em>price</em> and <em>sales_qty</em>. The correlation confirms it, … and makes it more precise.</p>
<p>Let us compute the correlation coefficient between advertising spend and the weekly sales from the <em>advertising_sales_channel</em> data frame. From <a href="#fig-advertising-sales-channel-1" class="quarto-xref">Figure&nbsp;<span>2.8</span></a> we saw that these two variables are positively related. Let us see what the correlation coefficient says.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>advertising_sales_channel <span class="sc">|&gt;</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">ad_sales_corr =</span> <span class="fu">cor</span>(advertising_spend_k, weekly_sales_k))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["ad_sales_corr"],"name":[1],"type":["dbl"],"align":["right"]}],"data":[{"1":"0.76"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>Sure enough, we see a positive correlation coefficient.</p>
</section>
<section id="perfect-correlation" class="level3" data-number="2.2.7">
<h3 data-number="2.2.7" class="anchored" data-anchor-id="perfect-correlation"><span class="header-section-number">2.2.7</span> Perfect correlation</h3>
<p>Consider <a href="#fig-price-demand-3" class="quarto-xref">Figure&nbsp;<span>2.10</span></a> showing strong, but imperfect, correlation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>price_demand <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(sales_qty <span class="sc">~</span> price)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-price-demand-3" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-price-demand-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="point-plots_files/figure-html/fig-price-demand-3-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-price-demand-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.10: Price and sales_qty are not perfectly correlated – correlation coefficient is -0.75
</figcaption>
</figure>
</div>
</div>
</div>
<p>We have already established that <em>price</em> and <em>sales_qty</em> are negatively related. That is, there is a general pattern that higher values of <em>price</em> have lower values of <em>sales_qty</em>.</p>
<p>In <a href="#fig-price-demand-3" class="quarto-xref">Figure&nbsp;<span>2.10</span></a>, if we look only at the points corresponding to a particular value of <em>price</em>, say 13, the points along this vertical line range from approximately 1100 to 1320. That is, given a value of <em>price</em>, we cannot be sure about the exact value of the corresponding value of <em>sales_qty</em>. However, knowing <em>price</em> does give us some idea about <em>sale_qty</em>. This shows relationship, but not perfect correlation.</p>
<p>When the correlation coefficient is +1 or -1, we have perfect correlation. In this case, knowing the value of one variable enables us to precisely know the value of the other variable as well. This happens when all the points lie on a straight line instead of being dispersed as a cloud as in <a href="#fig-price-demand-3" class="quarto-xref">Figure&nbsp;<span>2.10</span></a>.</p>
<div id="fig-production-cost-units-produced" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-production-cost-units-produced-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-production-cost-units-produced.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-production-cost-units-produced-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.11: Perfect correlation arises when all the points lie perfectly on a straight line – the variables in this plot have a corelation coefficient of +1
</figcaption>
</figure>
</div>
<p><a href="#fig-production-cost-units-produced" class="quarto-xref">Figure&nbsp;<span>2.11</span></a> shows a situation when all points lie on a perfect straight line. In this case, given a value for one variable, we can determine exactly the value of the other. We can determine it visually or by plugging the value of the known variable into the following equation and calculating the value of the other variable.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>total_cost <span class="ot">=</span> <span class="dv">10000</span> <span class="sc">+</span> <span class="dv">45</span><span class="sc">*</span>units_produced</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>In <a href="#fig-production-cost-units-produced" class="quarto-xref">Figure&nbsp;<span>2.11</span></a> the line slopes upward as it goes from left to right. WHen the line on which all points fall slopes down as it goes right, the correlation is still perfect, but the line slopes down as it goes to the right and so we have a correlation coefficien of -1.</p>
</section>
<section id="how-the-point-cloud-looks-for-various-correlation-coefficients" class="level3" data-number="2.2.8">
<h3 data-number="2.2.8" class="anchored" data-anchor-id="how-the-point-cloud-looks-for-various-correlation-coefficients"><span class="header-section-number">2.2.8</span> How the point cloud looks for various correlation coefficients</h3>
<p><a href="#fig-various-corr-coeffs" class="quarto-xref">Figure&nbsp;<span>2.12</span></a> shows the point plots for various values of correlation coefficients between -1 and +1.</p>
<div id="fig-various-corr-coeffs" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-various-corr-coeffs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-various-corr-coeffs.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-various-corr-coeffs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.12: Point plots for various correlation-coefficients (r)
</figcaption>
</figure>
</div>
<p>You can see the following: - in the plot wigth correlation coefficient = -1 (r = -1), the points align perfectly on a straight line <em>sloping downwards</em> as the x values increase - at +1 they align perfactly on a line <em>sloping upwards</em> as the x values increase - as the coefficient goes from -1 to 0, the points get more scattered away from perfect alignment on a straightline until at 0 there is no pattern whatsoever - as the correlation coefficient increases from 0 to +1, we see that the tendency to align on a straight line increases until perfect alignment at r = 1.</p>
</section>
</section>
<section id="plotting-a-numerical-variable-against-a-categorical-one" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="plotting-a-numerical-variable-against-a-categorical-one"><span class="header-section-number">2.3</span> Plotting a numerical variable against a categorical one</h2>
<p>In this course, we will only assign a numerical variable to the y-axis. Thus, if a plot has a categorical variable, it will only occupy the x-axis.</p>
<p>Numerical and categorical variables differ in how they behave in plots. In <a href="#fig-advertising-sales-channel-1" class="quarto-xref">Figure&nbsp;<span>2.8</span></a> we have the variable <em>advertising_spend_k</em> on the x-axis. Being a numerical variable, it can potentially take on any value on the x-axis. On the other hand, look at <a href="#fig-bank-account-type-balance" class="quarto-xref">Figure&nbsp;<span>2.13</span></a>.</p>
<div id="fig-bank-account-type-balance" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bank-account-type-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-bank-account-type-balance.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bank-account-type-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.13: Plotting a categorical variable against a numerical one – using the data frame <em>acct_type_balance</em> (not plotted using the <em>point_plot</em> function)
</figcaption>
</figure>
</div>
<p>Here we have the variable <em>bank_account_type</em> on the x-axis and it can take on only one of two values <em>“Checking”</em> and <em>“Savings”</em>. Thios is why each of the rows in the data frame falls along one of two perfectly vertical assortment of points If the row corresponds to a “Checking” account, it falls on the left set of points and on the right set otherwise.</p>
<section id="point_plot-and-jittering" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="point_plot-and-jittering"><span class="header-section-number">2.3.1</span> <em>point_plot</em> and “jittering”</h3>
<p>If we have two <em>Checking</em> accounts with the same or very similar balance, their points will overlap. Because of this overplotting, the plot in <a href="#fig-bank-account-type-balance" class="quarto-xref">Figure&nbsp;<span>2.13</span></a> does not enable us to look at all the points.</p>
<p>To overcome this problem, the <em>point_plot</em> function plots this chart a bit differently. See <a href="#fig-account-type-balance-point-plot" class="quarto-xref">Figure&nbsp;<span>2.14</span></a>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>acct_type_balance <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(balance <span class="sc">~</span> bank_account_type)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-account-type-balance-point-plot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-account-type-balance-point-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="point-plots_files/figure-html/fig-account-type-balance-point-plot-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-account-type-balance-point-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.14: Plot of account type against account bakance using the <em>point_plot function</em>: it jitters the points along the x-axis to reduce overplotting
</figcaption>
</figure>
</div>
</div>
</div>
<p>To enable us to see the points more clearly, the <em>point_plot</em> function randomly “jitters” the points along the x-axis to more clearly separate points that might be overplotted or close together.</p>
</section>
</section>
<section id="bringing-a-third-variable-into-the-plot" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="bringing-a-third-variable-into-the-plot"><span class="header-section-number">2.4</span> Bringing a third variable into the plot</h2>
<p>Two-dimensional plots can normally accommodate only two variables – one on each axis. However, we can often get more insights if we manage to get more variables into our plots. The <em>point_plot</em> functions allows us to bring one more dimension to our plots through color.</p>
<p>In <a href="#fig-advertising-sales-channel-1" class="quarto-xref">Figure&nbsp;<span>2.8</span></a>, we saw the positive relationship between <em>weekly_sales_k</em> and <em>advertising_spend_k</em> in the <em>advertising_sales_channel</em> data frame. That data frame has another variable <em>channel</em>. Each row corresponds to one of two sales channels – <em>Search Ads</em> and <em>Retail Promo</em>. We might want to study separately for each channel the relationship between advertising spend and the weekly sales.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>advertising_sales_channel <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(weekly_sales_k <span class="sc">~</span> advertising_spend_k <span class="sc">+</span> channel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-error">
<pre><code>Error in `fortify()`:
! `data` must be a &lt;data.frame&gt;, or an
  object coercible by `fortify()`, or a valid
  &lt;data.frame&gt;-like object coercible by
  `as.data.frame()`.
Caused by error in `check_data_frame_like()`:
! `colnames(data)` must return a
  &lt;character&gt; of length `ncol(data)`.</code></pre>
</div>
</div>
<p><span class="quarto-unresolved-ref">?fig-advertising-sales-channel-color</span> inserts, through color, the variable <em>channel</em> into the plot of <em>weekly_sales_k</em> against <em>advertising_spend_k</em> from the <em>advertising_sales_channel</em> data frame. From it we can clearly see that the points corresponding to each sales channel clearly shows the positive relationship that we saw earlier. But this plot also shows that for a given value of <em>advertising_spend_k</em> the <em>Retail Promo</em> channel generally has a comparatively higher <em>weekly_sales_k</em> value. Adding the variable <em>channel</em> through color enabled us to see more into the data than before.</p>
<section id="understanding-the-tilde-expression-to-add-a-third-variable" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="understanding-the-tilde-expression-to-add-a-third-variable"><span class="header-section-number">2.4.1</span> Understanding the tilde expression to add a third variable</h3>
<p><a href="#fig-color-tilde-expression" class="quarto-xref">Figure&nbsp;<span>2.15</span></a> shows the tilde expression we used in a point plot of two variables to color the points based on a third variable.</p>
<div id="fig-color-tilde-expression" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-color-tilde-expression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../images/fig-color-tilde-expression.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-color-tilde-expression-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2.15: To color the points based on the value of a third variable, we just <em>add</em> it to the end of the tilde-expression after a plus sign
</figcaption>
</figure>
</div>
<p><span class="quarto-unresolved-ref">?fig-color-tilde-expression-2</span> shows another example. In this, we use the <em>mpg</em> data frame which contains data on cars. We plot the city mileage of cars (variable <em>cty</em>) against their engine displacement (variable <em>displ</em>). We color each point based on the class of the vehicle (variable <em>class</em>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>mpg <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(cty <span class="sc">~</span> displ <span class="sc">+</span> class)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-error">
<pre><code>Error in `fortify()`:
! `data` must be a &lt;data.frame&gt;, or an
  object coercible by `fortify()`, or a valid
  &lt;data.frame&gt;-like object coercible by
  `as.data.frame()`.
Caused by error in `check_data_frame_like()`:
! `colnames(data)` must return a
  &lt;character&gt; of length `ncol(data)`.</code></pre>
</div>
</div>


<!-- -->

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../modules/01-data-visualization/data-frames.html" class="pagination-link" aria-label="Data Frames and Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data Frames and Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../modules/02-variability/02-overview.html" class="pagination-link" aria-label="Module 2: Variation">
        <span class="nav-page-text">Module 2: Variation</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Exploring Relationships through Scatterplots</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>The term *statistics* often conjures up thoughts of numerical computations. However, before we perform various co mputations, we often get a feel for the data and the underlying patterns by first visualizing the data. In this course we will use only a few standard plots to communicate essential statistical ideas. </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>In fact, use a single function -- *point_plot* -- to generate all of our plots. Although R offers numerous, sophisticated plotting features to plot almost anything we can imagine, we will keep things simple and focus only on what we need to support the concepts that our course covers.</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="fu">## Learning outcomes</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>After working though this chapter, you will be able to:</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>given a scatterplot of two numeric variables with the plot's axes labeled explain precisely what determines the location of a given point</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>given a scatterplot of two numeric variables, the data frame on which it is based, and a specific point on the plot, identify the corresponding row in the data frame</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>given a scatterplot of two numeric variables, the data frame on which it is based, and a specific row in the data frame,  identify the corresponding point on the plot</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>given a scatterplot one numeric variable on the y-axis against a categorical variable on the x-axis, explain how many different values exist for the x-axis</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>given a scatterplot one numeric variable on the y-axis against a categorical variable on the x-axis, explain the speific appearance of the points along the x-axis for each of the category levels</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>describe a tilde-expression (a model expression)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>given a tilde-expression with one variable on eithert side of the tilde, state how they relate to the plot axes</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>given a tidle expression with two variables on the right of the tilde, expalin the mnappings of the elements of the tidle expression to the elements of the plot</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>given a tidle expression with two variablkes on the right of the tilde, expalin the mnappings of the elements of the tidle expression to the elements of the plot</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>explain why the points are jittered along the x-axis when the x-axis has a categorical variable</span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Given a scatterplot of a num eric variable on the y-axis and a caregorical variable on the y-axis, identify a pair of points that would have overlapped if not for jittering</span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>use the point_plot function to</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>generate a scatterplot of two numeric variables</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>generate a scatterplot of one numeric variable on the y-axis against a categorical variable on the x-axis</span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>generate ascatterplot of numeric variables on both axes with the points colored based on a third variable</span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-33"><a href="#cb14-33" aria-hidden="true" tabindex="-1"></a><span class="ss">  - </span>generate ascatterplot of numeric variables on both axes with the points colored based on a third variable and the plots split into facets based on a fourth variable</span>
<span id="cb14-34"><a href="#cb14-34" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-35"><a href="#cb14-35" aria-hidden="true" tabindex="-1"></a><span class="fu">## Plotting the relationship between two numerical variables</span></span>
<span id="cb14-36"><a href="#cb14-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-37"><a href="#cb14-37" aria-hidden="true" tabindex="-1"></a>The *point_plot()* function that we will rely on for plots in this course lives in the *LSTbook* package. We will be using the *LSTextra*s package. Once we load the *LSTextras* package (which in turn loads the *LSTbook* package and all its dependencies), the *point_plot()* function becomes available for us to use. </span>
<span id="cb14-38"><a href="#cb14-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-39"><a href="#cb14-39" aria-hidden="true" tabindex="-1"></a>Let us first look at the *price_demand* data frame that is built into the *LSTbook* package.</span>
<span id="cb14-40"><a href="#cb14-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-41"><a href="#cb14-41" aria-hidden="true" tabindex="-1"></a>A hypothetical company has gathered data for a single product. Over time, and across very similar sales areas, the company has charged different prices for the same product, It has recorded the monthly sales for each price. The dataset *price_demand* contains the price and the corresponding sales quantities. We would like to study if the two variables *price* and *sales_qty* are related in any way. </span>
<span id="cb14-42"><a href="#cb14-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-43"><a href="#cb14-43" aria-hidden="true" tabindex="-1"></a>First let us see some rows from the dataset.</span>
<span id="cb14-44"><a href="#cb14-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-45"><a href="#cb14-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-46"><a href="#cb14-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-49"><a href="#cb14-49" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-50"><a href="#cb14-50" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb14-51"><a href="#cb14-51" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-price-demand</span></span>
<span id="cb14-52"><a href="#cb14-52" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Price Demand data (first 15 rows)"</span></span>
<span id="cb14-53"><a href="#cb14-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-54"><a href="#cb14-54" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">head</span>(price_demand, <span class="dv">15</span>), <span class="at">booktabs =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">latex_options =</span> <span class="st">"hold_position"</span>)</span>
<span id="cb14-55"><a href="#cb14-55" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-56"><a href="#cb14-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-57"><a href="#cb14-57" aria-hidden="true" tabindex="-1"></a>The full dataset has 500 rows. With so many rows, we cannot easily get a handle on the overall pattern by looking at the data directly. Visualizing the data might help us. We will do several things in this section:</span>
<span id="cb14-58"><a href="#cb14-58" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>generate the plot using R code</span>
<span id="cb14-59"><a href="#cb14-59" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>understand how each element of the plot is related to the original dataset</span>
<span id="cb14-60"><a href="#cb14-60" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>understand the various elements of the code so that you can use similar code to generate plots that you many need</span>
<span id="cb14-61"><a href="#cb14-61" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>interpret the plot</span>
<span id="cb14-62"><a href="#cb14-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-63"><a href="#cb14-63" aria-hidden="true" tabindex="-1"></a>The code and the plot appear below. For now, ignore the code. We will discuss it in detail after analyzing the plot itself.</span>
<span id="cb14-64"><a href="#cb14-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-67"><a href="#cb14-67" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-68"><a href="#cb14-68" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb14-69"><a href="#cb14-69" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-price-demand</span></span>
<span id="cb14-70"><a href="#cb14-70" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Price demand relationship"</span></span>
<span id="cb14-71"><a href="#cb14-71" aria-hidden="true" tabindex="-1"></a>price_demand <span class="sc">|&gt;</span> </span>
<span id="cb14-72"><a href="#cb14-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(sales_qty <span class="sc">~</span> price)</span>
<span id="cb14-73"><a href="#cb14-73" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-74"><a href="#cb14-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-75"><a href="#cb14-75" aria-hidden="true" tabindex="-1"></a>@fig-price-demand shows the relationship between *price* and *sales_qty* -- the two variables in the data frame. Note the following about the plot:</span>
<span id="cb14-76"><a href="#cb14-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-77"><a href="#cb14-77" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The plot has two axes -- the x-axis along the width and the y-axis along tbe height. </span>
<span id="cb14-78"><a href="#cb14-78" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The plot shows thge values of price on the x-axis and the values of sales_qty on the y-axis.</span>
<span id="cb14-79"><a href="#cb14-79" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>If you take any single point on the plot, you can drop a vertical line from the point to the x-axis and the point where it intersects the x-axis is the *price* corresponding to the point.</span>
<span id="cb14-80"><a href="#cb14-80" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Similarly, if you draw a horizontal line from the point to intersect the y-axis, you get the *sales_qty* corresponding to that point.</span>
<span id="cb14-81"><a href="#cb14-81" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Each point of the plot corresponds to one row of the dataset. So how many points are on the plot? 500, since the dataset has 500 rows. </span>
<span id="cb14-82"><a href="#cb14-82" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Thus given a point on the plot, we should be able to identify a corresponding row of the data frame</span>
<span id="cb14-83"><a href="#cb14-83" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Given a row of the data frame, we should be able to identify a corresponding point on the plot.</span>
<span id="cb14-84"><a href="#cb14-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-85"><a href="#cb14-85" aria-hidden="true" tabindex="-1"></a><span class="fu">### Finding the point corresponding to a row of the data frame</span></span>
<span id="cb14-86"><a href="#cb14-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-87"><a href="#cb14-87" aria-hidden="true" tabindex="-1"></a>Let us now try to find the point on the plot corrresponding to the first row in @fig-price-demand.</span>
<span id="cb14-88"><a href="#cb14-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-89"><a href="#cb14-89" aria-hidden="true" tabindex="-1"></a>The first row of the data frame has *price = 11.8* and *sales_qty = 1260*. Therefore, we can find the point by drawing a vertical line from 11.8 on the x-axis to intersect a horizontal line from 1260 on the y-axis. @fig-first-row-price-demand-on-plot illustrates this. We have highlighted the point by enlarging it.</span>
<span id="cb14-90"><a href="#cb14-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-91"><a href="#cb14-91" aria-hidden="true" tabindex="-1"></a><span class="al">![Finding the first row of the *price_demand* data frame on the plot: *price = 11.8*, *sales_qty =  1260*](../../images/fig-first-row-price-demand-on-plot.png)</span>{#fig-first-row-price-demand-on-plot width=70% fig-align="center"}</span>
<span id="cb14-92"><a href="#cb14-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-93"><a href="#cb14-93" aria-hidden="true" tabindex="-1"></a>Similarly, let us locate the point corresponding to row 11 (*price = 13.3*, *sales_qty = 1170*).</span>
<span id="cb14-94"><a href="#cb14-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-95"><a href="#cb14-95" aria-hidden="true" tabindex="-1"></a>following the same approach we arrive at @fig-eleventh-row-price-demand-on-plot.</span>
<span id="cb14-96"><a href="#cb14-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-97"><a href="#cb14-97" aria-hidden="true" tabindex="-1"></a><span class="al">![Finding the eleventh row of the *price_demand* data frame on the plot: *price = 13.3*, *sales_qty = 1170*](../../images/fig-eleventh-row-price-demand-on-plot.png)</span>{#fig-eleventh-row-price-demand-on-plot width=70% fig-align="center"}</span>
<span id="cb14-98"><a href="#cb14-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-99"><a href="#cb14-99" aria-hidden="true" tabindex="-1"></a><span class="fu">### Finding the *price* and *sales_qty* corresponding to a point on the plot</span></span>
<span id="cb14-100"><a href="#cb14-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-101"><a href="#cb14-101" aria-hidden="true" tabindex="-1"></a>We can reverse the above process to find the variable values (and hence the actual row) corresponding to a point on the plot. We will simply drop a vertical line from the point down to the x-axis to get the *price* and draw a horizontal line from the point to the y-axis to determine the *sales_qty*. The figure will look similar to the prior two figures.</span>
<span id="cb14-102"><a href="#cb14-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-103"><a href="#cb14-103" aria-hidden="true" tabindex="-1"></a><span class="fu">### Dissecting the code</span></span>
<span id="cb14-104"><a href="#cb14-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-105"><a href="#cb14-105" aria-hidden="true" tabindex="-1"></a>@fig-first-point-plot-code decodes the various elements of the code that we used to generate out first point plot in @fig-price-demand. We see that we pass the data frame *price_demand* to the *point_plot* function through the *pipe* operator. We add the tilde expression for the plot as an additional argument.</span>
<span id="cb14-106"><a href="#cb14-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-107"><a href="#cb14-107" aria-hidden="true" tabindex="-1"></a>@fig-basic-tilde-expression shows us that the *point_plot* function maps the variable on the left of the tilde operator to the y-axis of the plot and maps the variable to the right of the tilde expression to the x-axis of the plot.</span>
<span id="cb14-108"><a href="#cb14-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-109"><a href="#cb14-109" aria-hidden="true" tabindex="-1"></a><span class="al">![Passing the *price_demand* data frame as argument to the *point_plot* function through the pipe operator](../../images/fig-first-point-plot-code.png)</span>{#fig-first-point-plot-code width=70% fig-align="center"}</span>
<span id="cb14-110"><a href="#cb14-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-111"><a href="#cb14-111" aria-hidden="true" tabindex="-1"></a><span class="al">![Using a tilde expression to map variables to the axes](../../images/fig-basic-tilde-expression.png)</span>{#fig-basic-tilde-expression width=70% fig-align="center"}</span>
<span id="cb14-112"><a href="#cb14-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-113"><a href="#cb14-113" aria-hidden="true" tabindex="-1"></a><span class="fu">### Interpreting the plot</span></span>
<span id="cb14-114"><a href="#cb14-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-115"><a href="#cb14-115" aria-hidden="true" tabindex="-1"></a>@fig-price-demand-2 repeats the plot of *price* versus *sales_qty*. </span>
<span id="cb14-116"><a href="#cb14-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-119"><a href="#cb14-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-120"><a href="#cb14-120" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb14-121"><a href="#cb14-121" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-price-demand-2</span></span>
<span id="cb14-122"><a href="#cb14-122" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Price demand relationship (again)"</span></span>
<span id="cb14-123"><a href="#cb14-123" aria-hidden="true" tabindex="-1"></a>price_demand <span class="sc">|&gt;</span> </span>
<span id="cb14-124"><a href="#cb14-124" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(sales_qty <span class="sc">~</span> price)</span>
<span id="cb14-125"><a href="#cb14-125" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-126"><a href="#cb14-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-127"><a href="#cb14-127" aria-hidden="true" tabindex="-1"></a>We can see a clear trend showing that, in general, higher prices correspond to lower values of sales quantity. </span>
<span id="cb14-128"><a href="#cb14-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-129"><a href="#cb14-129" aria-hidden="true" tabindex="-1"></a>To be sure, this is only a trend and not a strict rule. That is, given any two points, we do not have a guarantee that the point with the higher price will always have a lower sales quantity. However, this will be true for most of the pairs of points. @fig-scatter-with-line-segments-1 illustrates this with some randomly selected pairs of points. We see that most of the lines point down and to the right -- meaning that for most pairs of points, the one with higher *price* has a lower *sales_qty*. However, we also see a few examples where the opposite is true. </span>
<span id="cb14-130"><a href="#cb14-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-131"><a href="#cb14-131" aria-hidden="true" tabindex="-1"></a>This is why we only calls this a *trend* and not a strict rule about the relationship between price and sales_qty.</span>
<span id="cb14-132"><a href="#cb14-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-133"><a href="#cb14-133" aria-hidden="true" tabindex="-1"></a><span class="al">![Line segments connecting some pairs of points showing that for most pairs of points the point with higher price has lower sales_qty](../../images/fig-scatter-with-line-segments-1.png)</span>{#fig-scatter-with-line-segments-1 width=70% fig-align="center"}</span>
<span id="cb14-134"><a href="#cb14-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-135"><a href="#cb14-135" aria-hidden="true" tabindex="-1"></a><span class="fu">### Positive and negative relationships</span></span>
<span id="cb14-136"><a href="#cb14-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-137"><a href="#cb14-137" aria-hidden="true" tabindex="-1"></a>In general, when we discuss the relationship between two numerical variables, if the general trend is that higher values of one correspond to higher values of the other, then we have a positive relationship. On the other hand, is higher values of one variable correspond to lower values of the other then we have a negative relationship.</span>
<span id="cb14-138"><a href="#cb14-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-139"><a href="#cb14-139" aria-hidden="true" tabindex="-1"></a>What kind of relationship does @fig-price-demand-2 show -- positive or negative?</span>
<span id="cb14-140"><a href="#cb14-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-141"><a href="#cb14-141" aria-hidden="true" tabindex="-1"></a>You got it right if you said *negative* -- higher values of *price* correspond to lower values of *sales_qty*.</span>
<span id="cb14-142"><a href="#cb14-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-143"><a href="#cb14-143" aria-hidden="true" tabindex="-1"></a>@fig-advertising-sales-channel-1 shows two positively correlated variables. Here, higher values of one variable are generally related to higher values of the other. We used the *advertising_sales_channel* data frame for this plot.</span>
<span id="cb14-144"><a href="#cb14-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-145"><a href="#cb14-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-148"><a href="#cb14-148" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-149"><a href="#cb14-149" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb14-150"><a href="#cb14-150" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-advertising-sales-channel-1</span></span>
<span id="cb14-151"><a href="#cb14-151" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Weekly sales and advertising spend have a positive relationship -- higher advertising generally has higher weekly sales"</span></span>
<span id="cb14-152"><a href="#cb14-152" aria-hidden="true" tabindex="-1"></a>advertising_sales_channel <span class="sc">|&gt;</span> </span>
<span id="cb14-153"><a href="#cb14-153" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(weekly_sales_k <span class="sc">~</span> advertising_spend_k)</span>
<span id="cb14-154"><a href="#cb14-154" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-155"><a href="#cb14-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-156"><a href="#cb14-156" aria-hidden="true" tabindex="-1"></a>The data frame *returns_dpo* contains hypothetical data on various firms' daily stock returns and the number of days they take to pay their suppliers. @fig-returns-dpo-1 shows the relationship between these variables. We cannot spot any trend. Higher or lower values of one variable do not indicate higher or lower values of the other. Hence there is neither a positive relationship nor a negative one.</span>
<span id="cb14-157"><a href="#cb14-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-160"><a href="#cb14-160" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-161"><a href="#cb14-161" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb14-162"><a href="#cb14-162" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-returns-dpo-1</span></span>
<span id="cb14-163"><a href="#cb14-163" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Days payment outstanding (dpo) does not have a relationship to the daily stock return"</span></span>
<span id="cb14-164"><a href="#cb14-164" aria-hidden="true" tabindex="-1"></a>returns_dpo <span class="sc">|&gt;</span> </span>
<span id="cb14-165"><a href="#cb14-165" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(daily_return <span class="sc">~</span> dpo)</span>
<span id="cb14-166"><a href="#cb14-166" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-167"><a href="#cb14-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-168"><a href="#cb14-168" aria-hidden="true" tabindex="-1"></a><span class="fu">### Putting a number on the relationship: The correlation coefficient </span></span>
<span id="cb14-169"><a href="#cb14-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-170"><a href="#cb14-170" aria-hidden="true" tabindex="-1"></a>Thus far, we have been talking about relationships between variables. Exact sciences like mathematics and statistics like to be precise and assign numbers where possible. Statistics commonly uses the *correlation coefficient* to quantify the relationship between two numerical variables. This section just introduces the *correlation coefficient* and shows you how to compute it using R. We will get into the mechanics of the actual computation later in the book.</span>
<span id="cb14-171"><a href="#cb14-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-172"><a href="#cb14-172" aria-hidden="true" tabindex="-1"></a>The correlation coefficient can take a value between -1 and +1. A value of 0 signifies a complete absence of relationship. -1 signifies a perfect negative correlation and +1 signifies a perfact positive correlation. We discuss these ideas below.</span>
<span id="cb14-173"><a href="#cb14-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-174"><a href="#cb14-174" aria-hidden="true" tabindex="-1"></a>We look at some examples now. Revisiting the *price_demand* data frame, let us use R to compute the correlation coefficient between the variables *price* and *sales_qty*. </span>
<span id="cb14-175"><a href="#cb14-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-178"><a href="#cb14-178" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-179"><a href="#cb14-179" aria-hidden="true" tabindex="-1"></a>price_demand <span class="sc">|&gt;</span> </span>
<span id="cb14-180"><a href="#cb14-180" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">price_sales_qty_correlation =</span> <span class="fu">cor</span>(price, sales_qty))</span>
<span id="cb14-181"><a href="#cb14-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-182"><a href="#cb14-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-183"><a href="#cb14-183" aria-hidden="true" tabindex="-1"></a>We are computing a summary and hence use the *summarize* function (see @sec-summarize-function). Since the summary we are computing now is the correlation coefficient, we use the *cor* function within the *summarize* function. We have chosen to call the comoputed result *price_sales_qty_correlation*. We could have named it anything we wanted, but chose the sensible approach of giving it a meaningul name.</span>
<span id="cb14-184"><a href="#cb14-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-185"><a href="#cb14-185" aria-hidden="true" tabindex="-1"></a>@fig-price-demand had already shown us the negative relationship between  *price* and *sales_qty*. The correlation confirms it, ... and makes it more precise.</span>
<span id="cb14-186"><a href="#cb14-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-187"><a href="#cb14-187" aria-hidden="true" tabindex="-1"></a>Let us compute the correlation coefficient between advertising spend and the weekly sales from the *advertising_sales_channel* data frame. From @fig-advertising-sales-channel-1 we saw that these two variables are positively related. Let us see what the correlation coefficient says.</span>
<span id="cb14-188"><a href="#cb14-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-191"><a href="#cb14-191" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-192"><a href="#cb14-192" aria-hidden="true" tabindex="-1"></a>advertising_sales_channel <span class="sc">|&gt;</span> </span>
<span id="cb14-193"><a href="#cb14-193" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">ad_sales_corr =</span> <span class="fu">cor</span>(advertising_spend_k, weekly_sales_k))</span>
<span id="cb14-194"><a href="#cb14-194" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-195"><a href="#cb14-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-196"><a href="#cb14-196" aria-hidden="true" tabindex="-1"></a>Sure enough, we see a positive correlation coefficient.</span>
<span id="cb14-197"><a href="#cb14-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-198"><a href="#cb14-198" aria-hidden="true" tabindex="-1"></a><span class="fu">### Perfect correlation</span></span>
<span id="cb14-199"><a href="#cb14-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-200"><a href="#cb14-200" aria-hidden="true" tabindex="-1"></a>Consider @fig-price-demand-3 showing strong, but imperfect, correlation.</span>
<span id="cb14-201"><a href="#cb14-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-204"><a href="#cb14-204" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-205"><a href="#cb14-205" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb14-206"><a href="#cb14-206" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-price-demand-3</span></span>
<span id="cb14-207"><a href="#cb14-207" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Price and sales_qty are not perfectly correlated -- correlation coefficient is -0.75 "</span></span>
<span id="cb14-208"><a href="#cb14-208" aria-hidden="true" tabindex="-1"></a>price_demand <span class="sc">|&gt;</span> </span>
<span id="cb14-209"><a href="#cb14-209" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(sales_qty <span class="sc">~</span> price)</span>
<span id="cb14-210"><a href="#cb14-210" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-211"><a href="#cb14-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-212"><a href="#cb14-212" aria-hidden="true" tabindex="-1"></a>We have already established that *price* and *sales_qty* are negatively related. That is, there is a general pattern that higher values of *price* have lower values of *sales_qty*.</span>
<span id="cb14-213"><a href="#cb14-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-214"><a href="#cb14-214" aria-hidden="true" tabindex="-1"></a>In @fig-price-demand-3, if we look only at the points corresponding to a particular value of *price*, say 13, the points along this vertical line range from approximately 1100 to 1320. That is, given a value of *price*, we cannot be sure about the exact value of the corresponding value of *sales_qty*. However, knowing  *price* does give us some idea about *sale_qty*. This shows relationship, but not perfect correlation.</span>
<span id="cb14-215"><a href="#cb14-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-216"><a href="#cb14-216" aria-hidden="true" tabindex="-1"></a>When the correlation coefficient is +1 or -1, we have perfect correlation. In this case, knowing the value of one variable enables us to precisely know the value of the other variable as well. This happens when all the points lie on a straight line instead of being dispersed as a cloud as in @fig-price-demand-3.</span>
<span id="cb14-217"><a href="#cb14-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-218"><a href="#cb14-218" aria-hidden="true" tabindex="-1"></a><span class="al">![Perfect correlation arises when all the points lie perfectly on a straight line -- the variables in this plot have a corelation coefficient of +1](../../images/fig-production-cost-units-produced.png)</span>{#fig-production-cost-units-produced width=70% fig-align="center"}</span>
<span id="cb14-219"><a href="#cb14-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-220"><a href="#cb14-220" aria-hidden="true" tabindex="-1"></a>@fig-production-cost-units-produced shows a situation when all points lie on a perfect straight line. In this case, given a value for one variable, we can determine exactly the value of the other. We can determine it visually or by plugging the value of the known variable into the following equation and calculating the value of the other variable.</span>
<span id="cb14-221"><a href="#cb14-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-224"><a href="#cb14-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-225"><a href="#cb14-225" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: FALSE</span></span>
<span id="cb14-226"><a href="#cb14-226" aria-hidden="true" tabindex="-1"></a>total_cost <span class="ot">=</span> <span class="dv">10000</span> <span class="sc">+</span> <span class="dv">45</span><span class="sc">*</span>units_produced</span>
<span id="cb14-227"><a href="#cb14-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-228"><a href="#cb14-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-229"><a href="#cb14-229" aria-hidden="true" tabindex="-1"></a>In @fig-production-cost-units-produced the line slopes upward as it goes from left to right. WHen the line on which all points fall slopes down as it goes right, the correlation is still perfect, but the line slopes down as it goes to the right and so we have a correlation coefficien of -1.</span>
<span id="cb14-230"><a href="#cb14-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-231"><a href="#cb14-231" aria-hidden="true" tabindex="-1"></a><span class="fu">### How the point cloud looks for various correlation coefficients</span></span>
<span id="cb14-232"><a href="#cb14-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-233"><a href="#cb14-233" aria-hidden="true" tabindex="-1"></a>@fig-various-corr-coeffs shows the point plots for various values of correlation coefficients between -1 and +1. </span>
<span id="cb14-234"><a href="#cb14-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-235"><a href="#cb14-235" aria-hidden="true" tabindex="-1"></a><span class="al">![Point plots for various correlation-coefficients (r)](../../images/fig-various-corr-coeffs.png)</span>{#fig-various-corr-coeffs width=70% fig-align="center"}</span>
<span id="cb14-236"><a href="#cb14-236" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-237"><a href="#cb14-237" aria-hidden="true" tabindex="-1"></a>You can see the following:</span>
<span id="cb14-238"><a href="#cb14-238" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>in the plot wigth correlation coefficient = -1 (r = -1), the points align perfectly on a straight line *sloping downwards* as the x values increase </span>
<span id="cb14-239"><a href="#cb14-239" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>at +1 they align perfactly on a line *sloping upwards* as the x values increase</span>
<span id="cb14-240"><a href="#cb14-240" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>as the coefficient goes from -1 to 0, the points get more scattered away from perfect alignment on a straightline until at 0 there is no pattern whatsoever</span>
<span id="cb14-241"><a href="#cb14-241" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>as the correlation coefficient increases from 0 to +1, we see that the tendency to align on a straight line increases until perfect alignment at r = 1.</span>
<span id="cb14-242"><a href="#cb14-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-243"><a href="#cb14-243" aria-hidden="true" tabindex="-1"></a><span class="fu">## Plotting a numerical variable against a categorical one</span></span>
<span id="cb14-244"><a href="#cb14-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-245"><a href="#cb14-245" aria-hidden="true" tabindex="-1"></a>In this course, we will only assign a numerical variable to the y-axis. Thus, if a plot has a categorical variable, it will only occupy the x-axis.</span>
<span id="cb14-246"><a href="#cb14-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-247"><a href="#cb14-247" aria-hidden="true" tabindex="-1"></a>Numerical and categorical variables differ in how they behave in plots. In @fig-advertising-sales-channel-1 we have the variable *advertising_spend_k* on the x-axis. Being a numerical variable, it can potentially take on any value on the x-axis. On the other hand, look at @fig-bank-account-type-balance. </span>
<span id="cb14-248"><a href="#cb14-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-249"><a href="#cb14-249" aria-hidden="true" tabindex="-1"></a><span class="al">![Plotting a categorical variable against a numerical one -- using the data frame *acct_type_balance* (not plotted using the *point_plot* function)](../../images/fig-bank-account-type-balance.png)</span>{#fig-bank-account-type-balance width=70% fig-align="center"}</span>
<span id="cb14-250"><a href="#cb14-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-251"><a href="#cb14-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-252"><a href="#cb14-252" aria-hidden="true" tabindex="-1"></a>Here we have the variable *bank_account_type* on the x-axis and it can take on only one of two values *"Checking"* and *"Savings"*. Thios is why each of the rows in the data frame falls along one of two perfectly vertical assortment of points If the row corresponds to a "Checking" account, it falls on the left set of points and on the right set otherwise. </span>
<span id="cb14-253"><a href="#cb14-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-254"><a href="#cb14-254" aria-hidden="true" tabindex="-1"></a><span class="fu">### *point_plot* and "jittering"</span></span>
<span id="cb14-255"><a href="#cb14-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-256"><a href="#cb14-256" aria-hidden="true" tabindex="-1"></a>If we have two *Checking* accounts with the same or very similar balance, their points will overlap. Because of this overplotting, the plot in @fig-bank-account-type-balance does not enable us to look at all the points.</span>
<span id="cb14-257"><a href="#cb14-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-258"><a href="#cb14-258" aria-hidden="true" tabindex="-1"></a>To overcome this problem, the *point_plot* function plots this chart a bit differently. See @fig-account-type-balance-point-plot.</span>
<span id="cb14-259"><a href="#cb14-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-262"><a href="#cb14-262" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-263"><a href="#cb14-263" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb14-264"><a href="#cb14-264" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-account-type-balance-point-plot</span></span>
<span id="cb14-265"><a href="#cb14-265" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Plot of account type against account bakance using the *point_plot function*: it jitters the points along the x-axis to reduce overplotting "</span></span>
<span id="cb14-266"><a href="#cb14-266" aria-hidden="true" tabindex="-1"></a>acct_type_balance <span class="sc">|&gt;</span> </span>
<span id="cb14-267"><a href="#cb14-267" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(balance <span class="sc">~</span> bank_account_type)</span>
<span id="cb14-268"><a href="#cb14-268" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-269"><a href="#cb14-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-270"><a href="#cb14-270" aria-hidden="true" tabindex="-1"></a>To enable us to see the points more clearly, the *point_plot* function randomly "jitters" the points along the x-axis to more clearly separate points that might be overplotted or close together.</span>
<span id="cb14-271"><a href="#cb14-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-272"><a href="#cb14-272" aria-hidden="true" tabindex="-1"></a><span class="fu">## Bringing a third variable into the plot</span></span>
<span id="cb14-273"><a href="#cb14-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-274"><a href="#cb14-274" aria-hidden="true" tabindex="-1"></a>Two-dimensional plots can normally accommodate only two variables -- one on each axis. However, we can often get more insights if we manage to get more variables into our plots. The *point_plot* functions allows us to bring one more dimension to our plots through color.  </span>
<span id="cb14-275"><a href="#cb14-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-276"><a href="#cb14-276" aria-hidden="true" tabindex="-1"></a>In @fig-advertising-sales-channel-1, we saw the positive relationship between *weekly_sales_k* and *advertising_spend_k* in the *advertising_sales_channel* data frame. That data frame has another variable *channel*. Each row corresponds to one of two sales channels -- *Search Ads* and *Retail Promo*. We might want to study separately for each channel the relationship between advertising spend and the weekly sales. </span>
<span id="cb14-277"><a href="#cb14-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-278"><a href="#cb14-278" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-281"><a href="#cb14-281" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-282"><a href="#cb14-282" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb14-283"><a href="#cb14-283" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: true</span></span>
<span id="cb14-284"><a href="#cb14-284" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-advertising-sales-channel-color</span></span>
<span id="cb14-285"><a href="#cb14-285" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "We bring in  *channel* through color in the plot of *weekly_sales_k* against *advertising_spend_k* from the *advertising_sales_channel* data frame"</span></span>
<span id="cb14-286"><a href="#cb14-286" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-287"><a href="#cb14-287" aria-hidden="true" tabindex="-1"></a>advertising_sales_channel <span class="sc">|&gt;</span> </span>
<span id="cb14-288"><a href="#cb14-288" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(weekly_sales_k <span class="sc">~</span> advertising_spend_k <span class="sc">+</span> channel)</span>
<span id="cb14-289"><a href="#cb14-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-290"><a href="#cb14-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-291"><a href="#cb14-291" aria-hidden="true" tabindex="-1"></a>@fig-advertising-sales-channel-color inserts, through color, the variable *channel* into the plot of *weekly_sales_k* against *advertising_spend_k* from the *advertising_sales_channel* data frame. From it we can clearly see that the points corresponding to each sales channel clearly shows the positive relationship that we saw earlier. But this plot also shows that for a given value of *advertising_spend_k* the *Retail Promo* channel generally has a comparatively higher *weekly_sales_k* value. Adding the variable *channel* through color enabled us to see more into the data than before.</span>
<span id="cb14-292"><a href="#cb14-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-293"><a href="#cb14-293" aria-hidden="true" tabindex="-1"></a><span class="fu">### Understanding the tilde expression to add a third variable</span></span>
<span id="cb14-294"><a href="#cb14-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-295"><a href="#cb14-295" aria-hidden="true" tabindex="-1"></a>@fig-color-tilde-expression shows the tilde expression we used in a point plot of two variables to color the points based on a third variable.</span>
<span id="cb14-296"><a href="#cb14-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-297"><a href="#cb14-297" aria-hidden="true" tabindex="-1"></a><span class="al">![To color the points based on the value of a third variable, we just *add* it to the end of the tilde-expression after a plus sign ](../../images/fig-color-tilde-expression.png)</span>{#fig-color-tilde-expression width=70% fig-align="center"}</span>
<span id="cb14-298"><a href="#cb14-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-299"><a href="#cb14-299" aria-hidden="true" tabindex="-1"></a>@fig-color-tilde-expression-2 shows another example. In this, we use the *mpg* data frame which contains data on cars. We plot the city mileage of cars (variable *cty*) against their engine displacement (variable *displ*). We color each point based on the class of the vehicle (variable *class*).</span>
<span id="cb14-300"><a href="#cb14-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-303"><a href="#cb14-303" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb14-304"><a href="#cb14-304" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: true</span></span>
<span id="cb14-305"><a href="#cb14-305" aria-hidden="true" tabindex="-1"></a><span class="co">#| error: true</span></span>
<span id="cb14-306"><a href="#cb14-306" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: fig-color-tilde-expression-2</span></span>
<span id="cb14-307"><a href="#cb14-307" aria-hidden="true" tabindex="-1"></a><span class="co">#| fig-cap: "Using the *mpg* data frame: plotting the city mileage against displacement and coloring the points based on the class of a car"</span></span>
<span id="cb14-308"><a href="#cb14-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-309"><a href="#cb14-309" aria-hidden="true" tabindex="-1"></a>mpg <span class="sc">|&gt;</span> </span>
<span id="cb14-310"><a href="#cb14-310" aria-hidden="true" tabindex="-1"></a>  <span class="fu">point_plot</span>(cty <span class="sc">~</span> displ <span class="sc">+</span> class)</span>
<span id="cb14-311"><a href="#cb14-311" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb14-312"><a href="#cb14-312" aria-hidden="true" tabindex="-1"></a></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>